// Program.cs  (Console app)
// Generates C# handler stubs + dispatcher switch from McpToolsetDefinition.json
//
// Usage:
//   dotnet run -- path/to/McpToolsetDefinition.json > GeneratedHandlers.cs
//
// Notes:
// - This is a SKETCH that is robust-ish against missing fields.
// - Adjust the JSON property names if your schema differs (e.g. "inputSchema" vs "x-inputSchema").
// - The generator outputs:
//     * a switch(method) dispatcher snippet
//     * one handler method per tool that parses params (very basic) and returns JsonNode stub
//
// Requires: <LangVersion>latest</LangVersion>

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
namespace MCPDispatcherGenerator
{

    internal class Program
    {
        static int Main(string[] args)
        {

            string? path;
            if (args.Length < 1) path = @"C:\Users\gerha\source\repos\ShapeIt\ShapeIt\McpToolsetDefinition.json";
            else path = args[0];
            var ns = GetArg(args, "--namespace") ?? "ShapeIt";
            var cls = GetArg(args, "--class") ?? "MCPServer";
            string? outputPath;
            outputPath = GetArg(args, "--output") ?? @"C:\Users\gerha\source\repos\ShapeIt\ShapeIt\MCPServer.Generated.cs";

            using var doc = JsonDocument.Parse(File.ReadAllText(path));
            var root = doc.RootElement;

            if (!TryGet(root, "tools", out var toolsEl) || toolsEl.ValueKind != JsonValueKind.Array)
            {
                Console.Error.WriteLine("No root.tools array found.");
                return 3;
            }

            var tools = toolsEl.EnumerateArray()
                .Select(ParseTool)
                .Where(t => !string.IsNullOrWhiteSpace(t.Method))
                .OrderBy(t => t.Method, StringComparer.Ordinal)
                .ToList();

            var sb = new StringBuilder();

            EmitHeader(sb, ns, cls, path);
            EmitDispatcher(sb, tools);
            EmitHandlers(sb, tools);
            EmitFooter(sb);

            Console.Write(sb.ToString());
            using (StreamWriter writer = File.CreateText(outputPath))
            {
                writer.WriteLine(sb.ToString());
            }


            ToolsetOutlineWriter.Generate(path, @"C:\Temp\JsonOutputTest.tst");
            return 0;
        }

        // ---------- Model ----------
        private sealed record ToolDef(
            string Method,
            string? Description,
            JsonElement? InputSchema,
            JsonElement? OutputSchema
        );

        private static ToolDef ParseTool(JsonElement toolEl)
        {
            // Common patterns: "name" or "method"
            var method =
                GetString(toolEl, "name") ??
                GetString(toolEl, "method") ??
                "";

            var desc = GetString(toolEl, "description");

            // Your file uses "x-outputSchema". Input schema name varies; try a few.
            JsonElement? input = null;
            if (TryGet(toolEl, "inputSchema", out var in1)) input = in1;
            else if (TryGet(toolEl, "x-inputSchema", out var in2)) input = in2;
            else if (TryGet(toolEl, "paramsSchema", out var in3)) input = in3;
            else if (TryGet(toolEl, "x-paramsSchema", out var in4)) input = in4;

            JsonElement? output = null;
            if (TryGet(toolEl, "x-outputSchema", out var out1)) output = out1;
            else if (TryGet(toolEl, "outputSchema", out var out2)) output = out2;

            return new ToolDef(method, desc, input, output);
        }

        // ---------- Emit ----------
        private static void EmitHeader(StringBuilder sb, string ns, string cls, string sourcePath)
        {
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"// Generated from: {Path.GetFileName(sourcePath)}");
            sb.AppendLine($"// Generated at:  {DateTimeOffset.Now:O}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("using System.Text.Json.Nodes;");
            sb.AppendLine("using CADability;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
            sb.AppendLine($"internal partial class {cls}");
            sb.AppendLine("{");
            sb.AppendLine("    // You are expected to provide these helpers somewhere in your server code:");
            sb.AppendLine("    // - JsonElement RequireObject(JsonElement root, string propName)");
            sb.AppendLine("    // - JsonElement RequireProperty(JsonElement obj, string propName)");
            sb.AppendLine("    // - string RequireString(JsonElement obj, string propName)");
            sb.AppendLine("    // - JsonElement? GetOptional(JsonElement obj, string propName)");
            sb.AppendLine("    // - string? GetOptionalString(JsonElement obj, string propName)");
            sb.AppendLine("    // - T RequireObjectRef<T>(JsonElement obj, string propName) where T : class");
            sb.AppendLine("    // - void ValidateEnum(string value, params string[] allowed)");
            sb.AppendLine();
        }

        private static void EmitFooter(StringBuilder sb)
        {
            sb.AppendLine("}");
        }

        private static void EmitDispatcher(StringBuilder sb, List<ToolDef> tools)
        {
            sb.AppendLine("    // ----- Dispatcher snippet -----");
            sb.AppendLine("    // Paste into your ProcessMethod switch(method) and adapt to your class:");
            sb.AppendLine("    public JsonNode DispatchGenerated(string method, JsonElement parameters)");
            sb.AppendLine("    {");
            sb.AppendLine("        return method switch");
            sb.AppendLine("        {");
            foreach (var t in tools)
            {
                var handlerName = MethodToHandlerName(t.Method);
                sb.AppendLine($"            \"{t.Method}\" => {handlerName}(parameters),");
            }
            sb.AppendLine("            _ => throw new JsonRpcException(-32601, $\"Method not found: {method}\")");
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void EmitHandlers(StringBuilder sb, List<ToolDef> tools)
        {
            sb.AppendLine("    // ----- Generated handlers (stubs) -----");
            foreach (var t in tools)
            {
                EmitHandler(sb, t);
                sb.AppendLine();
            }
        }

        private static void EmitHandler(StringBuilder sb, ToolDef tool)
        {
            var handlerName = MethodToHandlerName(tool.Method);
            var implName = handlerName + "Impl";

            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// {EscapeForXml(tool.Description ?? tool.Method)}");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    private JsonNode {handlerName}(JsonElement root)");
            sb.AppendLine("    {");
            sb.AppendLine("        AssertIsObject(root);");

            var paramVars = new List<string>();

            if (tool.InputSchema is { } inputSchema)
            {
                var required = GetStringArray(inputSchema, "required") ?? Array.Empty<string>();

                if (TryGet(inputSchema, "properties", out var props) && props.ValueKind == JsonValueKind.Object)
                {
                    foreach (var prop in props.EnumerateObject())
                    {
                        var propName = prop.Name;
                        var propSchema = prop.Value;
                        var isRequired = required.Contains(propName, StringComparer.Ordinal);

                        var varName = EmitParamReadAndReturnVarName(sb, propName, propSchema, isRequired);
                        paramVars.Add(varName);
                    }
                }
            }

            sb.AppendLine();
            sb.Append("        ");
            sb.Append(implName);
            sb.Append("(");
            sb.Append(string.Join(", ", paramVars));
            sb.AppendLine(");");
            sb.AppendLine();

            if (tool.OutputSchema is { } outputSchema && outputSchema.ValueKind == JsonValueKind.Object)
            {
                sb.AppendLine("        var result = new JsonObject();");
                EmitOutputScaffold(sb, "result", outputSchema, indent: "        ", depth: 0, maxDepth: 2);
                sb.AppendLine("        return result;");
            }
            else
            {
                sb.AppendLine("        return default;");
            }

            sb.AppendLine("    }");
        }

        private static string EmitParamReadAndReturnVarName(
            StringBuilder sb,
            string propName,
            JsonElement propSchema,
            bool isRequired)
        {
            var varName = SafeVarName(propName);
            string? refStr = null;
            if (TryGet(propSchema, "$ref", out var refEl) && refEl.ValueKind == JsonValueKind.String)
            {
                refStr = refEl.GetString() ?? "";
                if (refStr.EndsWith("/ObjectRef", StringComparison.Ordinal))
                {
                    var reader = isRequired
                        ? $"RequireObjectRef<object>(root, \"{propName}\");"
                        : $"(GetOptional(root, \"{propName}\") is {{ }} ? RequireObjectRef<object>(root, \"{propName}\") : null)";
                    sb.AppendLine($"        var {varName} = {reader};");
                    return varName;
                }
                if (refStr.EndsWith("/SketchRef", StringComparison.Ordinal))
                {
                    var reader = isRequired
                        ? $"RequireObjectRef<Sketch>(root, \"{propName}\");"
                        : $"(GetOptional(root, \"{propName}\") is {{ }} ? RequireObjectRef<object>(root, \"{propName}\") : null)";
                    sb.AppendLine($"        var {varName} = {reader};");
                    return varName;
                }
            }

            var type = GetString(propSchema, "type");

            if (type == "string")
            {
                if (isRequired) sb.AppendLine($"        var {varName} = RequireString(root, \"{propName}\");");
                else sb.AppendLine($"        var {varName} = GetOptionalString(root, \"{propName}\");");
                return varName;
            }
            if (type == "number")
            {
                double def = GetDoubleDefault(propSchema, "default");
                if (isRequired) sb.AppendLine($"        var {varName} = RequireNumber(root, \"{propName}\");");
                else sb.AppendLine($"        var {varName} = GetOptionalNumber(root, \"{propName}\", {def});");
                return varName;
            }
            if (type == "integer" || (refStr != null && refStr.EndsWith("/ExpressionInteger")))
            {
                int def = GetIntegerDefault(propSchema, "default");
                if (isRequired) sb.AppendLine($"        var {varName} = RequireInteger(root, \"{propName}\");");
                else sb.AppendLine($"        var {varName} = GetOptionalInteger(root, \"{propName}\", {def});");
                return varName;
            }
            if (type == "boolean" || (refStr != null && refStr.EndsWith("/ExpressionBool")))
            {
                bool def = GetBoolDefault(propSchema, "default");
                string defaultString = def ? "true" : "false";
                if (isRequired) sb.AppendLine($"        var {varName} = RequireBool(root, \"{propName}\");");
                else sb.AppendLine($"        var {varName} = GetOptionalBool(root, \"{propName}\", {defaultString});");
                return varName;
            }
            if (refStr != null && refStr.EndsWith("/Point3"))
            {
                if (isRequired) sb.AppendLine($"        var {varName} = RequirePoint3D(root, \"{propName}\");");
                else sb.AppendLine($"        var {varName} = GetOptionalPoint3D(root, \"{propName}\", GeoPoint.Invalid);");
                return varName;
            }
            if (refStr != null && refStr.EndsWith("/Point2"))
            {
                if (isRequired) sb.AppendLine($"        var {varName} = RequirePoint2D(root, \"{propName}\");");
                else sb.AppendLine($"        var {varName} = GetOptionalPoint2D(root, \"{propName}\", GeoPoint2D.Invalid);");
                return varName;
            }
            if (refStr != null && refStr.EndsWith("/Vec3"))
            {
                if (isRequired) sb.AppendLine($"        var {varName} = RequireVector3D(root, \"{propName}\");");
                else sb.AppendLine($"        var {varName} = GetOptionalVector3D(root, \"{propName}\", GeoVector.Invalid);");
                return varName;
            }
            if (refStr != null && refStr.EndsWith("/Vec2"))
            {
                if (isRequired) sb.AppendLine($"        var {varName} = RequireVector2D(root, \"{propName}\");");
                else sb.AppendLine($"        var {varName} = GetOptionalVector2D(root, \"{propName}\", GeoVector2D.Invalid);");
                return varName;
            }
            if (refStr != null && refStr.EndsWith("/Axis2"))
            {
                if (isRequired) sb.AppendLine($"        var {varName} = RequireAxis2D(root, \"{propName}\");");
                else sb.AppendLine($"        var {varName} = GetOptionalAxis2D(root, \"{propName}\", Axis2D.InvalidAxis);");
                return varName;
            }
            if (refStr != null && refStr.EndsWith("/Axis3"))
            {
                if (isRequired) sb.AppendLine($"        var {varName} = RequireAxis3D(root, \"{propName}\");");
                else sb.AppendLine($"        var {varName} = GetOptionalAxis3D(root, \"{propName}\", Axis.InvalidAxis);");
                return varName;
            }
            if (refStr != null && refStr.EndsWith("/Plane"))
            {
                if (isRequired) sb.AppendLine($"        var {varName} = RequirePlane(root, \"{propName}\");");
                else sb.AppendLine($"        var {varName} = GetOptionalPlane(root, \"{propName}\", Plane.Invalid);");
                return varName;
            }
            if (refStr != null && refStr.EndsWith("/Plane"))
            {
                if (isRequired) sb.AppendLine($"        var {varName} = RequirePlane(root, \"{propName}\");");
                else sb.AppendLine($"        var {varName} = GetOptionalPlane(root, \"{propName}\", Plane.Invalid);");
                return varName;
            }
            if (refStr != null && refStr.EndsWith("/ExpressionNumber"))
            {
                double def = GetDoubleDefault(propSchema, "default");
                string defString = double.IsNaN(def) ? "double.NaN" : def.ToString(System.Globalization.CultureInfo.InvariantCulture);
                if (isRequired) sb.AppendLine($"        var {varName} = RequireDouble(root, \"{propName}\");");
                else sb.AppendLine($"        var {varName} = GetOptionalDouble(root, \"{propName}\", {defString});");
                return varName;
            }
            if (refStr != null && refStr.EndsWith("/Angle"))
            {
                string? defString = null;
                double def = GetDoubleDefault(propSchema, "default");
                if (double.IsNaN(def))
                {
                    string? sdef = GetString(propSchema, "default");
                    if (sdef != null && sdef == "full") def = 360;
                }
                defString = double.IsNaN(def) ? "double.NaN" : def.ToString(System.Globalization.CultureInfo.InvariantCulture);
                if (isRequired) sb.AppendLine($"        var {varName} = RequireAngle(root, \"{propName}\");");
                else sb.AppendLine($"        var {varName} = GetOptionalDouble(root, \"{propName}\", {defString});");
                return varName;
            }

            if (isRequired) sb.AppendLine($"        var {varName} = RequireProperty(root, \"{propName}\");");
            else sb.AppendLine($"        var {varName} = GetOptional(root, \"{propName}\");");

            return varName;
        }

        private static void EmitOutputScaffold(StringBuilder sb, string objVar, JsonElement schema, string indent, int depth, int maxDepth)
        {
            // Very light scaffold: if schema.type == object and has properties, add nested JsonObject for properties (up to maxDepth).
            if (depth >= maxDepth) return;

            var type = GetString(schema, "type");
            if (type != "object") return;

            if (!TryGet(schema, "properties", out var props) || props.ValueKind != JsonValueKind.Object) return;

            foreach (var p in props.EnumerateObject())
            {
                var propName = p.Name;
                var propSchema = p.Value;
                var t = GetString(propSchema, "type");

                if (t == "object" && depth + 1 < maxDepth)
                {
                    sb.AppendLine($"{indent}{objVar}[\"{propName}\"] = new JsonObject();");
                    EmitOutputScaffold(sb, $"{objVar}[\"{propName}\"]!.AsObject()", propSchema, indent, depth + 1, maxDepth);
                }
                else if (t == "array")
                {
                    sb.AppendLine($"{indent}{objVar}[\"{propName}\"] = new JsonArray();");
                }
                else
                {
                    if (propName == "name") sb.AppendLine($"{indent}{objVar}[\"{propName}\"] = name;");
                    else if (propName == "id") sb.AppendLine($"{indent}{objVar}[\"{propName}\"] = GetNextId(name); // remove name when there is none");
                    else sb.AppendLine($"{indent}{objVar}[\"{propName}\"] = null; // TODO");
                }
            }
        }

        // ---------- Helpers ----------
        private static string MethodToHandlerName(string method)
        {
            // "sketch.boolean" -> "SketchBoolean"
            var parts = method.Split('.', StringSplitOptions.RemoveEmptyEntries);
            var s = string.Concat(parts.Select(Pascalize));
            return s.Length == 0 ? "Unnamed" : s;
        }

        private static string Pascalize(string s)
        {
            if (string.IsNullOrEmpty(s)) return s;
            var chunks = s.Split(new[] { '-', '_', ' ' }, StringSplitOptions.RemoveEmptyEntries);
            return string.Concat(chunks.Select(c => char.ToUpperInvariant(c[0]) + c.Substring(1)));
        }

        private static string SafeVarName(string propName)
        {
            // "face" -> "face"; "in" -> "@in"; "foo-bar" -> "fooBar"
            var s = propName;
            var parts = s.Split(new[] { '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);
            s = parts.Length == 0 ? "p" : parts[0] + string.Concat(parts.Skip(1).Select(Pascalize));
            // C# keyword escape (minimal list)
            return s is "class" or "namespace" or "params" or "event" or "in" or "out" or "ref"
                ? "@" + s
                : s;
        }

        private static string EscapeForXml(string s)
            => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

        private static string? GetArg(string[] args, string key)
        {
            for (int i = 0; i < args.Length - 1; i++)
                if (string.Equals(args[i], key, StringComparison.OrdinalIgnoreCase))
                    return args[i + 1];
            return null;
        }

        private static bool TryGet(JsonElement obj, string prop, out JsonElement value)
        {
            if (obj.ValueKind == JsonValueKind.Object && obj.TryGetProperty(prop, out value))
                return true;
            value = default;
            return false;
        }

        private static string? GetString(JsonElement obj, string prop)
            => TryGet(obj, prop, out var el) && el.ValueKind == JsonValueKind.String ? el.GetString() : null;
        private static bool GetBoolDefault(JsonElement obj, string prop)
            => TryGet(obj, prop, out var el) && el.ValueKind == JsonValueKind.True ? true : false;
        private static double GetDoubleDefault(JsonElement obj, string prop)
            => TryGet(obj, prop, out var el) && el.ValueKind == JsonValueKind.Number ? el.GetDouble() : double.NaN;
        private static int GetIntegerDefault(JsonElement obj, string prop)
            => TryGet(obj, prop, out var el) && el.ValueKind == JsonValueKind.Number ? el.GetInt32() : 0;


        private static string[]? GetStringArray(JsonElement obj, string prop)
        {
            if (!TryGet(obj, prop, out var el) || el.ValueKind != JsonValueKind.Array) return null;
            var list = new List<string>();
            foreach (var i in el.EnumerateArray())
                if (i.ValueKind == JsonValueKind.String && i.GetString() is { } s) list.Add(s);
            return list.ToArray();
        }
    }

    // You already have this (or similar) in your project:
    public sealed class JsonRpcException : Exception
    {
        public int Code { get; }
        public JsonRpcException(int code, string message) : base(message) => Code = code;
    }
}