// <auto-generated>
// Generated from: McpToolsetDefinition.json
// Generated at:  2026-03-12T21:41:41.4203531+01:00
// </auto-generated>

using System;
using System.Text.Json;
using System.Text.Json.Nodes;
using CADability;

namespace ShapeIt;

internal partial class MCPServer
{
    // You are expected to provide these helpers somewhere in your server code:
    // - JsonElement RequireObject(JsonElement root, string propName)
    // - JsonElement RequireProperty(JsonElement obj, string propName)
    // - string RequireString(JsonElement obj, string propName)
    // - JsonElement? GetOptional(JsonElement obj, string propName)
    // - string? GetOptionalString(JsonElement obj, string propName)
    // - T RequireObjectRef<T>(JsonElement obj, string propName) where T : class
    // - void ValidateEnum(string value, params string[] allowed)

    // ----- Dispatcher snippet -----
    // Paste into your ProcessMethod switch(method) and adapt to your class:
    public JsonNode DispatchGenerated(string method, JsonElement parameters)
    {
        return method switch
        {
            "assert.check" => AssertCheck(parameters),
            "document.commit_objects" => DocumentCommitObjects(parameters),
            "document.get_state" => DocumentGetState(parameters),
            "feature.chamfer" => FeatureChamfer(parameters),
            "feature.fillet" => FeatureFillet(parameters),
            "feature.hole" => FeatureHole(parameters),
            "feature.split" => FeatureSplit(parameters),
            "pattern.circular_sketch" => PatternCircularSketch(parameters),
            "pattern.circular_solids" => PatternCircularSolids(parameters),
            "pattern.grid_sketch" => PatternGridSketch(parameters),
            "pattern.grid_solids" => PatternGridSolids(parameters),
            "sketch.add_arc" => SketchAddArc(parameters),
            "sketch.add_circle" => SketchAddCircle(parameters),
            "sketch.add_ellipse" => SketchAddEllipse(parameters),
            "sketch.add_ellipse_arc" => SketchAddEllipseArc(parameters),
            "sketch.add_line" => SketchAddLine(parameters),
            "sketch.add_nurbs" => SketchAddNurbs(parameters),
            "sketch.add_polycurve" => SketchAddPolycurve(parameters),
            "sketch.add_rectangle" => SketchAddRectangle(parameters),
            "sketch.add_regular_polygon" => SketchAddRegularPolygon(parameters),
            "sketch.add_slot" => SketchAddSlot(parameters),
            "sketch.add_text" => SketchAddText(parameters),
            "sketch.angle_bisector" => SketchAngleBisector(parameters),
            "sketch.boolean" => SketchBoolean(parameters),
            "sketch.connect" => SketchConnect(parameters),
            "sketch.create" => SketchCreate(parameters),
            "sketch.create_on_face" => SketchCreateOnFace(parameters),
            "sketch.foot_point_on_curve" => SketchFootPointOnCurve(parameters),
            "sketch.get_vertices" => SketchGetVertices(parameters),
            "sketch.intersections" => SketchIntersections(parameters),
            "sketch.offset" => SketchOffset(parameters),
            "sketch.perpendicular_through" => SketchPerpendicularThrough(parameters),
            "sketch.round_vertices" => SketchRoundVertices(parameters),
            "solid.boolean" => SolidBoolean(parameters),
            "solid.box" => SolidBox(parameters),
            "solid.capsule" => SolidCapsule(parameters),
            "solid.cone" => SolidCone(parameters),
            "solid.cylinder" => SolidCylinder(parameters),
            "solid.extrude" => SolidExtrude(parameters),
            "solid.pipe" => SolidPipe(parameters),
            "solid.rotate" => SolidRotate(parameters),
            "solid.ruled" => SolidRuled(parameters),
            "solid.sphere" => SolidSphere(parameters),
            "solid.sweep" => SolidSweep(parameters),
            "solid.torus" => SolidTorus(parameters),
            "surface.nurbs" => SurfaceNurbs(parameters),
            "surface.parametric" => SurfaceParametric(parameters),
            "system.get_info" => SystemGetInfo(parameters),
            "transform.move" => TransformMove(parameters),
            "transform.reflect" => TransformReflect(parameters),
            "transform.rotate" => TransformRotate(parameters),
            "transform.scale" => TransformScale(parameters),
            "undo.begin" => UndoBegin(parameters),
            "undo.cancel" => UndoCancel(parameters),
            "undo.end" => UndoEnd(parameters),
            "workspace.delete" => WorkspaceDelete(parameters),
            "workspace.set" => WorkspaceSet(parameters),
            _ => throw new JsonRpcException(-32601, $"Method not found: {method}")
        };
    }

    // ----- Generated handlers (stubs) -----
    /// <summary>
    /// Checks a global boolean expression or validates a condition for all objects selected by a selector/query. If the check fails, the batch stops with an error.
    /// </summary>
    private JsonNode AssertCheck(JsonElement root)
    {
        AssertIsObject(root);
        var objects = GetOptional(root, "objects");
        var condition = GetOptionalString(root, "condition");
        var minCount = GetOptionalInteger(root, "minCount", -1);
        var maxCount = GetOptionalInteger(root, "maxCount", -1);
        var message = GetOptionalString(root, "message");
        var name = GetOptionalString(root, "name");

        AssertCheckImpl(objects, condition, minCount, maxCount, message, name);

        return new JsonObject();
    }

    /// <summary>
    /// Commits one or more workspace objects into the document model (so they appear in the model tree and will be saved). Returns committed object ids. Note: objects are resolved via Selector (may select one or many).
    /// </summary>
    private JsonNode DocumentCommitObjects(JsonElement root)
    {
        AssertIsObject(root);
        var objects = RequireProperty(root, "objects");

        DocumentCommitObjectsImpl(objects);

        var result = new JsonObject();
        result["committed"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Returns document state: active units (length), active selection, and current document version counter (monotonic).
    /// </summary>
    private JsonNode DocumentGetState(JsonElement root)
    {
        AssertIsObject(root);

        DocumentGetStateImpl();

        var result = new JsonObject();
        result["docVersion"] = null; // TODO
        result["lengthUnit"] = null; // TODO
        result["selection"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Chamfers the specified edges of a solid. Edges can be selected by named sets, queries, or set expressions. Supports automatic topology rebind (default: rebind=true) after the operation so that named faces/edges remain usable across feature/boolean changes. For an unsymmetric chamfer you must provide 'primaryFace' and 'secondaryDistance'
    /// </summary>
    private JsonNode FeatureChamfer(JsonElement root)
    {
        AssertIsObject(root);
        var solid = RequireProperty(root, "solid");
        var edges = RequireProperty(root, "edges");
        var distance = RequireDouble(root, "distance");
        var primaryFace = GetOptional(root, "primaryFace");
        var secondaryDistance = GetOptionalDouble(root, "secondaryDistance", double.NaN);
        var name = GetOptionalString(root, "name");
        var rebind = GetOptionalBool(root, "rebind", true);
        var rebindTargets = GetOptional(root, "rebindTargets");

        FeatureChamferImpl(solid, edges, distance, primaryFace, secondaryDistance, name, rebind, rebindTargets);

        var result = new JsonObject();
        result["feature"] = new JsonObject();
        result["feature"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["feature"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Rounds (fillets) the specified edges of a solid. Edges can be selected by ids, named sets, queries, or set expressions. Supports automatic topology rebind (default: rebind=true) after the operation so that named faces/edges remain usable across feature/boolean changes.
    /// </summary>
    private JsonNode FeatureFillet(JsonElement root)
    {
        AssertIsObject(root);
        var solid = RequireProperty(root, "solid");
        var edges = RequireProperty(root, "edges");
        var radius = RequireDouble(root, "radius");
        var name = GetOptionalString(root, "name");
        var rebind = GetOptionalBool(root, "rebind", true);
        var rebindTargets = GetOptional(root, "rebindTargets");

        FeatureFilletImpl(solid, edges, radius, name, rebind, rebindTargets);

        var result = new JsonObject();
        result["feature"] = new JsonObject();
        result["feature"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["feature"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Creates a cylindrical hole on a planar face of a solid. centerOnFace uses face-local UV coordinates (0,0 is face origin). Optionally captures created topology outputs as named sets. Supports automatic topology rebind (default: rebind=true) after the operation so that named faces/edges remain usable across feature/boolean changes. Note: solid is resolved via Selector (expected single solid). Note: face is resolved via Selector (expected single face).
    /// </summary>
    private JsonNode FeatureHole(JsonElement root)
    {
        AssertIsObject(root);
        var solid = RequireProperty(root, "solid");
        var face = RequireProperty(root, "face");
        var centerOnFace = GetOptional(root, "centerOnFace");
        var center = GetOptionalPoint3D(root, "center", GeoPoint.Invalid);
        var diameter = RequireDouble(root, "diameter");
        var through = GetOptionalBool(root, "through", true);
        var depth = GetOptionalDouble(root, "depth", double.NaN);
        var name = GetOptionalString(root, "name");
        var capture = GetOptional(root, "capture");
        var rebind = GetOptionalBool(root, "rebind", true);
        var rebindTargets = GetOptional(root, "rebindTargets");

        FeatureHoleImpl(solid, face, centerOnFace, center, diameter, through, depth, name, capture, rebind, rebindTargets);

        var result = new JsonObject();
        result["feature"] = new JsonObject();
        result["feature"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["feature"]!.AsObject()["name"] = name;
        result["outputs"] = new JsonObject();
        result["outputs"]!.AsObject()["entryEdges"] = new JsonArray();
        result["outputs"]!.AsObject()["exitEdges"] = new JsonArray();
        result["outputs"]!.AsObject()["wallFaces"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Split a solid by a separating surface. Currently, splitBy is a plane. The selected solid is divided into parts on the two sides of the plane. Parts on the side pointed to by the plane normal are considered outer; parts on the opposite side are considered inner. Result solids are only created for the sides for which a target name is provided. This allows efficient batch processing when only one side of the split is needed. Note: solid is resolved via Selector and must identify exactly one solid.
    /// </summary>
    private JsonNode FeatureSplit(JsonElement root)
    {
        AssertIsObject(root);
        var solid = RequireProperty(root, "solid");
        var splitBy = RequirePlane(root, "splitBy");
        var nameInner = GetOptionalString(root, "nameInner");
        var nameOuter = GetOptionalString(root, "nameOuter");
        var rebind = GetOptionalBool(root, "rebind", true);
        var rebindTargets = GetOptional(root, "rebindTargets");

        FeatureSplitImpl(solid, splitBy, nameInner, nameOuter, rebind, rebindTargets);

        var result = new JsonObject();
        result["dumy"] = null; // TODO
        return result;
    }

    /// <summary>
    /// Creates a circular pattern of sketch geometry around a 2D center point in sketch coordinates. If angle is omitted, a full 360° pattern is created. If merge=true, attempts to merge/boolean overlapping closed sketch geometry where applicable. If name is provided and nameWithSuffix=false, the name can refer to the whole result set; if nameWithSuffix=true, each created entity is named with a suffix.
    /// </summary>
    private JsonNode PatternCircularSketch(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var sketchGeometry = RequireProperty(root, "sketchGeometry");
        var center = RequirePoint2D(root, "center");
        var count = RequireInteger(root, "count");
        var angle = GetOptionalDouble(root, "angle", double.NaN);
        var merge = GetOptionalBool(root, "merge", false);
        var name = GetOptionalString(root, "name");
        var nameWithSuffix = GetOptionalBool(root, "nameWithSuffix", false);

        PatternCircularSketchImpl(sketch, sketchGeometry, center, count, angle, merge, name, nameWithSuffix);

        var result = new JsonObject();
        result["sketchGeometry"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Creates a circular pattern of solids around a 3D axis passing through center. If angle is omitted, defaults to 360 degrees. If name is provided, it refers to the whole resulting set. If suffix is true, individual solids are also named using &lt;base&gt;_&lt;n&gt; where &lt;base&gt; is name (if provided) or the source object's name.
    /// </summary>
    private JsonNode PatternCircularSolids(JsonElement root)
    {
        AssertIsObject(root);
        var solids = RequireProperty(root, "solids");
        var center = RequirePoint3D(root, "center");
        var axis = RequireVector3D(root, "axis");
        var count = RequireInteger(root, "count");
        var angle = GetOptionalDouble(root, "angle", 360);
        var copy = GetOptionalBool(root, "copy", true);
        var name = GetOptionalString(root, "name");
        var suffix = GetOptionalBool(root, "suffix", false);

        PatternCircularSolidsImpl(solids, center, axis, count, angle, copy, name, suffix);

        var result = new JsonObject();
        result["solids"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Creates a rectangular/grid pattern of sketch geometry. Step vectors are given in sketch plane coordinates (2D), allowing arbitrary directions (not limited to horizontal/vertical). If merge=true, attempts to merge/boolean overlapping closed sketch geometry where applicable. If name is provided and nameWithSuffix=false, the name can refer to the whole result set; if nameWithSuffix=true, each created entity is named with a suffix.
    /// </summary>
    private JsonNode PatternGridSketch(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var sketchGeometry = RequireProperty(root, "sketchGeometry");
        var countX = RequireInteger(root, "countX");
        var countY = RequireInteger(root, "countY");
        var stepX = RequireProperty(root, "stepX");
        var stepY = RequireProperty(root, "stepY");
        var merge = GetOptionalBool(root, "merge", false);
        var name = GetOptionalString(root, "name");
        var nameWithSuffix = GetOptionalBool(root, "nameWithSuffix", false);

        PatternGridSketchImpl(sketch, sketchGeometry, countX, countY, stepX, stepY, merge, name, nameWithSuffix);

        var result = new JsonObject();
        result["sketchGeometry"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Creates a rectangular or linear grid pattern of solids using 3D step vectors. If 'name' is provided, it refers to the entire resulting set. If 'suffix' is true, individual solids are also named using &lt;base&gt;_&lt;nx&gt;_&lt;ny&gt; (or &lt;base&gt;_&lt;n&gt; if one dimension equals 1), where &lt;base&gt; is 'name' (if provided) or the source object's name.
    /// </summary>
    private JsonNode PatternGridSolids(JsonElement root)
    {
        AssertIsObject(root);
        var solids = RequireProperty(root, "solids");
        var countX = RequireInteger(root, "countX");
        var countY = GetOptionalInteger(root, "countY", 0);
        var countXNegative = GetOptionalInteger(root, "countXNegative", 0);
        var countYNegative = GetOptionalInteger(root, "countYNegative", 0);
        var stepX = RequireVector3D(root, "stepX");
        var stepY = GetOptionalVector3D(root, "stepY", GeoVector.Invalid);
        var copy = GetOptionalBool(root, "copy", true);
        var name = GetOptionalString(root, "name");
        var suffix = GetOptionalBool(root, "suffix", false);

        PatternGridSolidsImpl(solids, countX, countY, countXNegative, countYNegative, stepX, stepY, copy, name, suffix);

        var result = new JsonObject();
        result["solids"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Adds an arc entity to a sketch.
    /// </summary>
    private JsonNode SketchAddArc(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var center = GetOptionalPoint2D(root, "center", GeoPoint2D.Invalid);
        var radius = GetOptionalDouble(root, "radius", double.NaN);
        var startAngleDeg = GetOptionalDouble(root, "startAngleDeg", double.NaN);
        var sweepAngleDeg = GetOptionalDouble(root, "sweepAngleDeg", double.NaN);
        var start = GetOptionalPoint2D(root, "start", GeoPoint2D.Invalid);
        var end = GetOptionalPoint2D(root, "end", GeoPoint2D.Invalid);
        var middle = GetOptionalPoint2D(root, "middle", GeoPoint2D.Invalid);
        var ccw = GetOptionalBool(root, "ccw", false);
        var name = GetOptionalString(root, "name");

        SketchAddArcImpl(sketch, center, radius, startAngleDeg, sweepAngleDeg, start, end, middle, ccw, name);

        return new JsonObject();
    }

    /// <summary>
    /// Adds a circle entity to a sketch.
    /// </summary>
    private JsonNode SketchAddCircle(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var center = GetOptionalPoint2D(root, "center", GeoPoint2D.Invalid);
        var radius = GetOptionalDouble(root, "radius", double.NaN);
        var diameter = GetOptionalDouble(root, "diameter", double.NaN);
        var name = GetOptionalString(root, "name");

        SketchAddCircleImpl(sketch, center, radius, diameter, name);

        return new JsonObject();
    }

    /// <summary>
    /// Adds an ellipse entity to a sketch.
    /// </summary>
    private JsonNode SketchAddEllipse(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var center = GetOptionalPoint2D(root, "center", GeoPoint2D.Invalid);
        var radiusMajor = GetOptionalDouble(root, "radiusMajor", double.NaN);
        var radiusMinor = GetOptionalDouble(root, "radiusMinor", double.NaN);
        var rotationDeg = GetOptionalDouble(root, "rotationDeg", 0);
        var name = GetOptionalString(root, "name");

        SketchAddEllipseImpl(sketch, center, radiusMajor, radiusMinor, rotationDeg, name);

        return new JsonObject();
    }

    /// <summary>
    /// Adds an elliptical arc entity to a sketch.
    /// </summary>
    private JsonNode SketchAddEllipseArc(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var center = GetOptionalPoint2D(root, "center", GeoPoint2D.Invalid);
        var radiusMajor = RequireDouble(root, "radiusMajor");
        var radiusMinor = RequireDouble(root, "radiusMinor");
        var rotationDeg = GetOptionalDouble(root, "rotationDeg", 0);
        var startAngleDeg = RequireDouble(root, "startAngleDeg");
        var sweepAngleDeg = RequireDouble(root, "sweepAngleDeg");
        var name = GetOptionalString(root, "name");

        SketchAddEllipseArcImpl(sketch, center, radiusMajor, radiusMinor, rotationDeg, startAngleDeg, sweepAngleDeg, name);

        return new JsonObject();
    }

    /// <summary>
    /// Adds a line entity to a sketch.
    /// </summary>
    private JsonNode SketchAddLine(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var start = RequirePoint2D(root, "start");
        var end = RequirePoint2D(root, "end");
        var name = GetOptionalString(root, "name");

        SketchAddLineImpl(sketch, start, end, name);

        return new JsonObject();
    }

    /// <summary>
    /// Adds a NURBS curve to a sketch.
    /// </summary>
    private JsonNode SketchAddNurbs(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var degree = GetOptionalInteger(root, "degree", 0);
        var controlPoints = GetOptional(root, "controlPoints");
        var throughPoints = GetOptional(root, "throughPoints");
        var knots = GetOptional(root, "knots");
        var weights = GetOptional(root, "weights");
        var isPeriodic = GetOptionalBool(root, "isPeriodic", false);
        var approximation = GetOptional(root, "approximation");
        var name = GetOptionalString(root, "name");

        SketchAddNurbsImpl(sketch, degree, controlPoints, throughPoints, knots, weights, isPeriodic, approximation, name);

        return new JsonObject();
    }

    /// <summary>
    /// Adds a polycurve entity to a sketch.
    /// </summary>
    private JsonNode SketchAddPolycurve(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var vertices = GetOptional(root, "vertices");
        var isClosed = GetOptionalBool(root, "isClosed", false);
        var name = GetOptionalString(root, "name");

        SketchAddPolycurveImpl(sketch, vertices, isClosed, name);

        return new JsonObject();
    }

    /// <summary>
    /// Adds a rectangle entity to a sketch.
    /// </summary>
    private JsonNode SketchAddRectangle(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var width = GetOptionalDouble(root, "width", double.NaN);
        var height = GetOptionalDouble(root, "height", double.NaN);
        var cornerRadius = GetOptionalDouble(root, "cornerRadius", 0);
        var center = GetOptionalPoint2D(root, "center", GeoPoint2D.Invalid);
        var rotationDeg = GetOptionalDouble(root, "rotationDeg", 0);
        var name = GetOptionalString(root, "name");

        SketchAddRectangleImpl(sketch, width, height, cornerRadius, center, rotationDeg, name);

        return new JsonObject();
    }

    /// <summary>
    /// Adds a regular polygon entity to a sketch.
    /// </summary>
    private JsonNode SketchAddRegularPolygon(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var center = GetOptionalPoint2D(root, "center", GeoPoint2D.Invalid);
        var innerRadius = GetOptionalDouble(root, "innerRadius", double.NaN);
        var outerRadius = GetOptionalDouble(root, "outerRadius", double.NaN);
        var sides = GetOptionalInteger(root, "sides", 0);
        var rotationDeg = GetOptionalDouble(root, "rotationDeg", 0);
        var name = GetOptionalString(root, "name");

        SketchAddRegularPolygonImpl(sketch, center, innerRadius, outerRadius, sides, rotationDeg, name);

        return new JsonObject();
    }

    /// <summary>
    /// Adds a slot entity to a sketch.
    /// </summary>
    private JsonNode SketchAddSlot(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var center = GetOptionalPoint2D(root, "center", GeoPoint2D.Invalid);
        var length = GetOptionalDouble(root, "length", double.NaN);
        var width = GetOptionalDouble(root, "width", double.NaN);
        var rotationDeg = GetOptionalDouble(root, "rotationDeg", double.NaN);
        var name = GetOptionalString(root, "name");

        SketchAddSlotImpl(sketch, center, length, width, rotationDeg, name);

        return new JsonObject();
    }

    /// <summary>
    /// Adds text to a sketch and converts it to sketch geometry as closed outline contours, including inner islands where present. The text is placed in sketch coordinates and is always oriented horizontally along the sketch x-axis.
    /// </summary>
    private JsonNode SketchAddText(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var text = RequireString(root, "text");
        var location = RequirePoint2D(root, "location");
        var height = RequireDouble(root, "height");
        var font = RequireProperty(root, "font");
        var horizontalAlign = GetOptional(root, "horizontalAlign");
        var verticalAlign = GetOptional(root, "verticalAlign");
        var characterSpacing = GetOptionalDouble(root, "characterSpacing", double.NaN);
        var wordSpacing = GetOptionalDouble(root, "wordSpacing", double.NaN);
        var name = GetOptionalString(root, "name");

        SketchAddTextImpl(sketch, text, location, height, font, horizontalAlign, verticalAlign, characterSpacing, wordSpacing, name);

        var result = new JsonObject();
        result["sketchGeometry"] = new JsonObject();
        result["sketchGeometry"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["sketchGeometry"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Creates an angle bisector line between two intersecting lines in a sketch.
    /// </summary>
    private JsonNode SketchAngleBisector(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var a = RequireProperty(root, "a");
        var b = RequireProperty(root, "b");
        var which = GetOptionalString(root, "which");
        var at = GetOptionalPoint2D(root, "at", GeoPoint2D.Invalid);
        var length = GetOptionalDouble(root, "length", 1);
        var name = GetOptionalString(root, "name");

        SketchAngleBisectorImpl(sketch, a, b, which, at, length, name);

        return new JsonObject();
    }

    /// <summary>
    /// Performs a 2D boolean on sketch entities/regions and returns a new region object. Inputs are treated as closed planar regions in the sketch plane.
    /// </summary>
    private JsonNode SketchBoolean(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var op = RequireString(root, "op");
        var inputs = RequireProperty(root, "inputs");
        var subtract = GetOptional(root, "subtract");
        var name = GetOptionalString(root, "name");

        SketchBooleanImpl(sketch, op, inputs, subtract, name);

        var result = new JsonObject();
        result["region"] = new JsonObject();
        result["region"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["region"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Connects open sketch entities into continuous chains/contours when endpoints match within precision. If entities is omitted, considers all eligible entities in the sketch. If closeGaps=true, remaining gaps are closed by inserting straight line segments (useful e.g. to close a 'C' shape made from two concentric arcs). If name is omitted, the operation overwrites the original entity/entities; if name is provided, the original remains and new connected entities are created.
    /// </summary>
    private JsonNode SketchConnect(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var sketchGeometry = GetOptional(root, "sketchGeometry");
        var precision = RequireDouble(root, "precision");
        var closeGaps = GetOptionalBool(root, "closeGaps", false);
        var name = GetOptionalString(root, "name");

        SketchConnectImpl(sketch, sketchGeometry, precision, closeGaps, name);

        var result = new JsonObject();
        result["affectedCount"] = null; // TODO
        result["contourCount"] = null; // TODO
        result["sketchGeometry"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Creates a new sketch on a plane. Returns sketchId.
    /// </summary>
    private JsonNode SketchCreate(JsonElement root)
    {
        AssertIsObject(root);
        var plane = RequirePlane(root, "plane");
        var name = GetOptionalString(root, "name");

        SketchCreateImpl(plane, name);

        var result = new JsonObject();
        result["sketch"] = new JsonObject();
        result["sketch"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["sketch"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Creates a new sketch attached to a planar face. Returns sketchId and the derived sketch plane. Note: face is resolved via Selector (expected single face).
    /// </summary>
    private JsonNode SketchCreateOnFace(JsonElement root)
    {
        AssertIsObject(root);
        var face = RequireProperty(root, "face");
        var point = GetOptionalPoint3D(root, "point", GeoPoint.Invalid);
        var xAxis = GetOptionalVector3D(root, "xAxis", GeoVector.Invalid);
        var name = GetOptionalString(root, "name");

        SketchCreateOnFaceImpl(face, point, xAxis, name);

        var result = new JsonObject();
        result["sketch"] = new JsonObject();
        result["sketch"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["sketch"]!.AsObject()["name"] = name;
        result["plane"] = null; // TODO
        return result;
    }

    /// <summary>
    /// Computes the closest orthogonal foot point of a given point onto a curve in a sketch.
    /// </summary>
    private JsonNode SketchFootPointOnCurve(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var point = RequirePoint2D(root, "point");
        var curve = RequireProperty(root, "curve");
        var mode = GetOptionalString(root, "mode");
        var clamp = GetOptionalBool(root, "clamp", false);
        var name = GetOptionalString(root, "name");
        var captured = GetOptional(root, "captured");

        SketchFootPointOnCurveImpl(sketch, point, curve, mode, clamp, name, captured);

        return new JsonObject();
    }

    /// <summary>
    /// Returns vertices of sketch geometry in sketch coordinates (2D). Vertices are derived from the topology of the selected sketch entities/regions (e.g., polycurve/rectangle/ngon vertices, arc/line endpoints, and region boundary vertices after boolean/offset operations). If 'sketchGeometry' is omitted, all eligible entities in the sketch are processed. If 'name' is provided, the resulting vertex set is stored in the workspace under this name. If 'suffix' is true, individual vertices are also stored as workspace points named &lt;base&gt;_&lt;i&gt; (0-based), where &lt;base&gt; is 'name'. The operation may return multiple disjoint vertex loops; vertices are returned in a deterministic order per loop as provided by the kernel.
    /// </summary>
    private JsonNode SketchGetVertices(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var sketchGeometry = GetOptional(root, "sketchGeometry");
        var name = GetOptionalString(root, "name");
        var suffix = GetOptionalBool(root, "suffix", false);
        var includeEndpoints = GetOptionalBool(root, "includeEndpoints", true);
        var unique = GetOptionalBool(root, "unique", false);
        var tolerance = GetOptionalDouble(root, "tolerance", double.NaN);

        SketchGetVerticesImpl(sketch, sketchGeometry, name, suffix, includeEndpoints, unique, tolerance);

        var result = new JsonObject();
        result["loops"] = new JsonArray();
        result["vertexCount"] = null; // TODO
        result["captured"] = new JsonObject();
        result["captured"]!.AsObject()["setName"] = null; // TODO
        result["captured"]!.AsObject()["vertexNames"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Computes intersection points between two sketch geometries.
    /// </summary>
    private JsonNode SketchIntersections(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var a = RequireProperty(root, "a");
        var b = RequireProperty(root, "b");
        var mode = GetOptionalString(root, "mode");
        var tolerance = GetOptionalDouble(root, "tolerance", double.NaN);
        var name = GetOptionalString(root, "name");
        var suffix = GetOptionalBool(root, "suffix", true);

        SketchIntersectionsImpl(sketch, a, b, mode, tolerance, name, suffix);

        return new JsonObject();
    }

    /// <summary>
    /// Offsets sketch geometry by a given signed distance. Closed inputs produce parallel contours (region offsets). Open inputs produce equidistant curves. For open curves, positive distance offsets to the right side of the curve parameter direction, negative distance to the left side. If 'makeRegion' is true and the input is open, the tool attempts to create a closed region by combining the original curve and its offset (connecting corresponding end points). The operation may produce multiple disjoint results, including regions with holes, depending on the input geometry and distance. If 'sketchGeometry' is omitted, all eligible entities in the sketch are offset.
    /// </summary>
    private JsonNode SketchOffset(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var sketchGeometry = GetOptional(root, "sketchGeometry");
        var distance = RequireDouble(root, "distance");
        var joinType = GetOptionalString(root, "joinType");
        var miterLimit = GetOptionalDouble(root, "miterLimit", double.NaN);
        var makeRegion = GetOptionalBool(root, "makeRegion", false);
        var capType = GetOptionalString(root, "capType");
        var name = GetOptionalString(root, "name");

        SketchOffsetImpl(sketch, sketchGeometry, distance, joinType, miterLimit, makeRegion, capType, name);

        var result = new JsonObject();
        result["sketchGeometry"] = new JsonArray();
        result["createdCount"] = null; // TODO
        return result;
    }

    /// <summary>
    /// Creates a line perpendicular to a given line through a specified point.
    /// </summary>
    private JsonNode SketchPerpendicularThrough(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var line = RequireProperty(root, "line");
        var point = RequirePoint2D(root, "point");
        var length = GetOptionalDouble(root, "length", 1);
        var name = GetOptionalString(root, "name");

        SketchPerpendicularThroughImpl(sketch, line, point, length, name);

        return new JsonObject();
    }

    /// <summary>
    /// Rounds (fillets) vertices of sketch entities. If entity is omitted, applies to all eligible entities in the sketch. Vertex selection can be done by proximity points (2D) or by vertex indices (for entities with an ordered vertex list such as polycurve/rectangle/ngon). If neither points nor indices are provided, all vertices are rounded. If name is omitted, the operation overwrites the original entity (same name as the source). If name is provided, a new entity is created and the original remains.
    /// </summary>
    private JsonNode SketchRoundVertices(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var entity = GetOptional(root, "entity");
        var radius = RequireDouble(root, "radius");
        var nearPoints = GetOptional(root, "nearPoints");
        var indices = GetOptional(root, "indices");
        var tolerance = GetOptionalDouble(root, "tolerance", double.NaN);
        var name = GetOptionalString(root, "name");

        SketchRoundVerticesImpl(sketch, entity, radius, nearPoints, indices, tolerance, name);

        var result = new JsonObject();
        result["affectedCount"] = null; // TODO
        result["sketchGeometry"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Performs a boolean operation on solids. The first operand is the target (and defines the default name). The second operand can be a single solid or a list of solids. Does not modify inputs; returns a new solid. Supports automatic topology rebind (default: rebind=true) after the operation so that named faces/edges remain usable across boolean changes.
    /// </summary>
    private JsonNode SolidBoolean(JsonElement root)
    {
        AssertIsObject(root);
        var op = RequireString(root, "op");
        var a = RequireProperty(root, "a");
        var b = RequireProperty(root, "b");
        var name = GetOptionalString(root, "name");
        var rebind = GetOptionalBool(root, "rebind", true);
        var rebindTargets = GetOptional(root, "rebindTargets");

        SolidBooleanImpl(op, a, b, name, rebind, rebindTargets);

        var result = new JsonObject();
        result["solid"] = new JsonObject();
        result["solid"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["solid"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Creates a box solid defined by an origin point and three edge lengths along a local coordinate system.
    /// </summary>
    private JsonNode SolidBox(JsonElement root)
    {
        AssertIsObject(root);
        var origin = RequirePoint3D(root, "origin");
        var axisX = GetOptionalVector3D(root, "axisX", GeoVector.Invalid);
        var axisY = GetOptionalVector3D(root, "axisY", GeoVector.Invalid);
        var sizeX = RequireDouble(root, "sizeX");
        var sizeY = RequireDouble(root, "sizeY");
        var sizeZ = RequireDouble(root, "sizeZ");
        var name = GetOptionalString(root, "name");

        SolidBoxImpl(origin, axisX, axisY, sizeX, sizeY, sizeZ, name);

        return new JsonObject();
    }

    /// <summary>
    /// Creates a capsule solid defined by two axis points and a radius.
    /// </summary>
    private JsonNode SolidCapsule(JsonElement root)
    {
        AssertIsObject(root);
        var start = RequirePoint3D(root, "start");
        var end = RequirePoint3D(root, "end");
        var radius = RequireDouble(root, "radius");
        var cap = GetOptionalString(root, "cap");
        var coneTipDistance = GetOptionalDouble(root, "coneTipDistance", double.NaN);
        var name = GetOptionalString(root, "name");

        SolidCapsuleImpl(start, end, radius, cap, coneTipDistance, name);

        return new JsonObject();
    }

    /// <summary>
    /// Creates a cone or conical frustum solid.
    /// </summary>
    private JsonNode SolidCone(JsonElement root)
    {
        AssertIsObject(root);
        var start = RequirePoint3D(root, "start");
        var end = RequirePoint3D(root, "end");
        var radiusStart = RequireDouble(root, "radiusStart");
        var radiusEnd = RequireDouble(root, "radiusEnd");
        var name = GetOptionalString(root, "name");

        SolidConeImpl(start, end, radiusStart, radiusEnd, name);

        return new JsonObject();
    }

    /// <summary>
    /// Creates a cylinder solid defined by two axis points and a radius.
    /// </summary>
    private JsonNode SolidCylinder(JsonElement root)
    {
        AssertIsObject(root);
        var start = RequirePoint3D(root, "start");
        var end = RequirePoint3D(root, "end");
        var radius = RequireDouble(root, "radius");
        var name = GetOptionalString(root, "name");

        SolidCylinderImpl(start, end, radius, name);

        return new JsonObject();
    }

    /// <summary>
    /// Extrudes a profile into a new solid body. direction defaults to profile/sketch normal. The extrusion spans from offset to offset+length along direction. If pitch is provided, performs a helical (screw-like) extrusion around the axis. Returns the new solid. Optionally captures start/end faces and profile-edge loops as named sets. Note: profile is resolved via Selector (expected sketch geometry or sketch with closed loops).
    /// </summary>
    private JsonNode SolidExtrude(JsonElement root)
    {
        AssertIsObject(root);
        var profile = RequireProperty(root, "profile");
        var length = RequireDouble(root, "length");
        var direction = GetOptionalVector3D(root, "direction", GeoVector.Invalid);
        var name = GetOptionalString(root, "name");
        var offset = GetOptionalDouble(root, "offset", 0);
        var pitch = GetOptionalDouble(root, "pitch", 0);
        var capture = GetOptional(root, "capture");

        SolidExtrudeImpl(profile, length, direction, name, offset, pitch, capture);

        var result = new JsonObject();
        result["solid"] = new JsonObject();
        result["solid"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["solid"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Creates a hollow cylindrical pipe solid.
    /// </summary>
    private JsonNode SolidPipe(JsonElement root)
    {
        AssertIsObject(root);
        var start = RequirePoint3D(root, "start");
        var end = RequirePoint3D(root, "end");
        var outerRadius = RequireDouble(root, "outerRadius");
        var innerRadius = RequireDouble(root, "innerRadius");
        var name = GetOptionalString(root, "name");

        SolidPipeImpl(start, end, outerRadius, innerRadius, name);

        return new JsonObject();
    }

    /// <summary>
    /// Revolves a planar profile around an axis to create a new solid body (revolve). angle can be full rotation or degrees. Returns the new solid. For partial revolves, start/end cap faces may be captured. Note: profile is resolved via Selector.
    /// </summary>
    private JsonNode SolidRotate(JsonElement root)
    {
        AssertIsObject(root);
        var profile = RequireProperty(root, "profile");
        var axis = RequireAxis3D(root, "axis");
        var angle = RequireAngle(root, "angle");
        var name = GetOptionalString(root, "name");
        var capture = GetOptional(root, "capture");

        SolidRotateImpl(profile, axis, angle, name, capture);

        var result = new JsonObject();
        result["solid"] = new JsonObject();
        result["solid"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["solid"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Creates a solid by connecting two closed sketch profiles with ruled surfaces. Corresponding points on the two profiles are connected by straight line segments. The profiles must be closed sketch geometries.
    /// </summary>
    private JsonNode SolidRuled(JsonElement root)
    {
        AssertIsObject(root);
        var profile1 = RequireProperty(root, "profile1");
        var profile2 = RequireProperty(root, "profile2");
        var synchronization = GetOptionalString(root, "synchronization");
        var alignment = GetOptionalString(root, "alignment");
        var matchPoints1 = GetOptional(root, "matchPoints1");
        var matchPoints2 = GetOptional(root, "matchPoints2");
        var name = GetOptionalString(root, "name");

        SolidRuledImpl(profile1, profile2, synchronization, alignment, matchPoints1, matchPoints2, name);

        return new JsonObject();
    }

    /// <summary>
    /// Creates a sphere solid. The sphere can be defined using different equivalent parameter sets.
    /// </summary>
    private JsonNode SolidSphere(JsonElement root)
    {
        AssertIsObject(root);
        var center = GetOptionalPoint3D(root, "center", GeoPoint.Invalid);
        var radius = GetOptionalDouble(root, "radius", double.NaN);
        var points = GetOptional(root, "points");
        var name = GetOptionalString(root, "name");

        SolidSphereImpl(center, radius, points, name);

        return new JsonObject();
    }

    /// <summary>
    /// Sweeps a profile along a path curve to create a new solid body. Path is a 3D curve or polycurve. Orientation defaults to 'follow' (Frenet/transport). Returns the new solid. Optionally captures start/end faces and profile-edge loops. Note: profile is resolved via Selector. Note: path is resolved via Selector (expected single path/curve).
    /// </summary>
    private JsonNode SolidSweep(JsonElement root)
    {
        AssertIsObject(root);
        var profile = RequireProperty(root, "profile");
        var path = RequireProperty(root, "path");
        var orientation = GetOptionalString(root, "orientation");
        var name = GetOptionalString(root, "name");
        var capture = GetOptional(root, "capture");

        SolidSweepImpl(profile, path, orientation, name, capture);

        var result = new JsonObject();
        result["solid"] = new JsonObject();
        result["solid"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["solid"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Creates a torus solid defined by center, axis, major radius and minor radius.
    /// </summary>
    private JsonNode SolidTorus(JsonElement root)
    {
        AssertIsObject(root);
        var center = RequirePoint3D(root, "center");
        var axis = RequireVector3D(root, "axis");
        var majorRadius = RequireDouble(root, "majorRadius");
        var minorRadius = RequireDouble(root, "minorRadius");
        var name = GetOptionalString(root, "name");

        SolidTorusImpl(center, axis, majorRadius, minorRadius, name);

        return new JsonObject();
    }

    /// <summary>
    /// Creates a NURBS surface from control points, knot vectors and optional weights. The resulting surface can be used as an unbounded carrier surface for later operations such as solid splitting.
    /// </summary>
    private JsonNode SurfaceNurbs(JsonElement root)
    {
        AssertIsObject(root);
        var degreeU = RequireInteger(root, "degreeU");
        var degreeV = RequireInteger(root, "degreeV");
        var controlPoints = RequireProperty(root, "controlPoints");
        var uKnots = RequireProperty(root, "uKnots");
        var vKnots = RequireProperty(root, "vKnots");
        var weights = GetOptional(root, "weights");
        var uPeriodic = GetOptionalBool(root, "uPeriodic", false);
        var vPeriodic = GetOptionalBool(root, "vPeriodic", false);
        var name = GetOptionalString(root, "name");

        SurfaceNurbsImpl(degreeU, degreeV, controlPoints, uKnots, vKnots, weights, uPeriodic, vPeriodic, name);

        return new JsonObject();
    }

    /// <summary>
    /// Creates a parametric surface from three expressions x(u,v), y(u,v), z(u,v) over a rectangular parameter domain. The surface is internally approximated by a NURBS surface and can be used as an unbounded carrier surface for later operations such as solid splitting.
    /// </summary>
    private JsonNode SurfaceParametric(JsonElement root)
    {
        AssertIsObject(root);
        var degreeU = GetOptionalInteger(root, "degreeU", 3);
        var degreeV = GetOptionalInteger(root, "degreeV", 3);
        var approximation = RequireProperty(root, "approximation");
        var name = GetOptionalString(root, "name");

        SurfaceParametricImpl(degreeU, degreeV, approximation, name);

        return new JsonObject();
    }

    /// <summary>
    /// Returns information about the active MCP toolset definition loaded by the server.
    /// </summary>
    private JsonNode SystemGetInfo(JsonElement root)
    {
        AssertIsObject(root);

        SystemGetInfoImpl();

        var result = new JsonObject();
        result["toolsetId"] = null; // TODO
        result["toolsetVersion"] = null; // TODO
        result["schemaVersion"] = null; // TODO
        result["generatedAt"] = null; // TODO
        result["toolsHash"] = null; // TODO
        return result;
    }

    /// <summary>
    /// Translates one or more objects by a 3D vector. If copy=true, returns new objects; otherwise modifies originals. Returned objects are references to moved/copied objects. When copy=true, the server can also copy named topology references (copyNamed=true) and create new names using nameSuffix. Note: objects are resolved via Selector (may select one or many).
    /// </summary>
    private JsonNode TransformMove(JsonElement root)
    {
        AssertIsObject(root);
        var objects = RequireProperty(root, "objects");
        var delta = RequireVector3D(root, "delta");
        var name = GetOptionalString(root, "name");
        var copySuffix = GetOptionalString(root, "copySuffix");

        TransformMoveImpl(objects, delta, name, copySuffix);

        var result = new JsonObject();
        result["objects"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Reflects (mirrors) one or more objects across a plane. If copy=true, returns new objects; otherwise modifies originals. When copy=true, the server can also copy named topology references (copyNamed=true) and create new names using nameSuffix. Note: objects are resolved via Selector (may select one or many).
    /// </summary>
    private JsonNode TransformReflect(JsonElement root)
    {
        AssertIsObject(root);
        var objects = RequireProperty(root, "objects");
        var plane = GetOptionalPlane(root, "plane", Plane.Invalid);
        var axis3D = GetOptionalAxis3D(root, "axis3D", Axis.InvalidAxis);
        var axis2D = GetOptionalAxis2D(root, "axis2D", Axis2D.InvalidAxis);
        var name = GetOptionalString(root, "name");
        var copySuffix = GetOptionalString(root, "copySuffix");

        TransformReflectImpl(objects, plane, axis3D, axis2D, name, copySuffix);

        var result = new JsonObject();
        result["objects"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Rotates one or more objects around an axis by a given angle. If 'name' is omitted, the selected objects are rotated in place and keep their names. If 'name' is provided, copies are created, rotated, and captured as a named set. When multiple objects are copied, individual result names are derived from the original names by appending 'nameSuffix'.
    /// </summary>
    private JsonNode TransformRotate(JsonElement root)
    {
        AssertIsObject(root);
        var objects = RequireProperty(root, "objects");
        var axis = RequireAxis3D(root, "axis");
        var angle = RequireAngle(root, "angle");
        var name = GetOptionalString(root, "name");
        var copySuffix = GetOptionalString(root, "copySuffix");

        TransformRotateImpl(objects, axis, angle, name, copySuffix);

        var result = new JsonObject();
        result["objects"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Scales one or more objects about an origin. Provide either uniform factor or non-uniform factors (x,y,z). If copy=true, returns new objects; otherwise modifies originals. When copy=true, the server can also copy named topology references (copyNamed=true) and create new names using nameSuffix. Note: objects are resolved via Selector (may select one or many).
    /// </summary>
    private JsonNode TransformScale(JsonElement root)
    {
        AssertIsObject(root);
        var objects = RequireProperty(root, "objects");
        var origin = RequirePoint3D(root, "origin");
        var factor = GetOptionalDouble(root, "factor", double.NaN);
        var factors = GetOptional(root, "factors");
        var name = GetOptionalString(root, "name");
        var copySuffix = GetOptionalString(root, "copySuffix");

        TransformScaleImpl(objects, origin, factor, factors, name, copySuffix);

        var result = new JsonObject();
        result["objects"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Begins an undo frame. All subsequent committed changes until undo.end are grouped into one undo step. Returns undoFrameId.
    /// </summary>
    private JsonNode UndoBegin(JsonElement root)
    {
        AssertIsObject(root);
        var label = RequireString(root, "label");

        UndoBeginImpl(label);

        var result = new JsonObject();
        result["undoFrameId"] = null; // TODO
        return result;
    }

    /// <summary>
    /// Cancels an undo frame started with undo.begin, rolling back all changes in that frame.
    /// </summary>
    private JsonNode UndoCancel(JsonElement root)
    {
        AssertIsObject(root);
        var undoFrameId = RequireString(root, "undoFrameId");

        UndoCancelImpl(undoFrameId);

        return new JsonObject();
    }

    /// <summary>
    /// Ends an undo frame started with undo.begin. If errors occurred, server may auto-cancel the frame.
    /// </summary>
    private JsonNode UndoEnd(JsonElement root)
    {
        AssertIsObject(root);
        var undoFrameId = RequireString(root, "undoFrameId");

        UndoEndImpl(undoFrameId);

        return new JsonObject();
    }

    /// <summary>
    /// Deletes one or more workspace objects (temporary objects not yet committed). Deleting a committed object is not allowed and returns E_INVALID_PARAMS. Note: objects are resolved via Selector (may select one or many).
    /// </summary>
    private JsonNode WorkspaceDelete(JsonElement root)
    {
        AssertIsObject(root);
        var objects = RequireProperty(root, "objects");

        WorkspaceDeleteImpl(objects);

        return new JsonObject();
    }

    /// <summary>
    /// Defines or updates a named workspace value. Optionally, the value can be marked as a user-editable parameter with UI metadata such as label, input type, limits, and choices.
    /// </summary>
    private JsonNode WorkspaceSet(JsonElement root)
    {
        AssertIsObject(root);
        var name = RequireString(root, "name");
        var value = RequireProperty(root, "value");
        var label = GetOptionalString(root, "label");
        var input = GetOptional(root, "input");

        WorkspaceSetImpl(name, value, label, input);

        var result = new JsonObject();
        result["name"] = name;
        return result;
    }

}

