// <auto-generated>
// Generated from: McpToolsetDefinition.json
// Generated at:  2026-02-20T20:50:49.4163217+01:00
// </auto-generated>

using System;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace ShapeIt;

internal partial class MCPServer
{
    // You are expected to provide these helpers somewhere in your server code:
    // - JsonElement RequireObject(JsonElement root, string propName)
    // - JsonElement RequireProperty(JsonElement obj, string propName)
    // - string RequireString(JsonElement obj, string propName)
    // - JsonElement? GetOptional(JsonElement obj, string propName)
    // - string? GetOptionalString(JsonElement obj, string propName)
    // - T RequireObjectRef<T>(JsonElement obj, string propName) where T : class
    // - void ValidateEnum(string value, params string[] allowed)

    // ----- Dispatcher snippet -----
    // Paste into your ProcessMethod switch(method) and adapt to your class:
    public JsonNode DispatchGenerated(string method, JsonElement parameters)
    {
        return method switch
        {
            "doc.commit_objects" => DocCommitObjects(parameters),
            "doc.get_state" => DocGetState(parameters),
            "feature.fillet_edges" => FeatureFilletEdges(parameters),
            "feature.hole" => FeatureHole(parameters),
            "pattern.circular_entities" => PatternCircularEntities(parameters),
            "pattern.circular_objects" => PatternCircularObjects(parameters),
            "pattern.grid_entities" => PatternGridEntities(parameters),
            "pattern.grid_objects" => PatternGridObjects(parameters),
            "pattern.inset_rectangle_points" => PatternInsetRectanglePoints(parameters),
            "sketch.add_entity" => SketchAddEntity(parameters),
            "sketch.boolean" => SketchBoolean(parameters),
            "sketch.connect" => SketchConnect(parameters),
            "sketch.create" => SketchCreate(parameters),
            "sketch.create_on_face" => SketchCreateOnFace(parameters),
            "sketch.round_vertices" => SketchRoundVertices(parameters),
            "solid.boolean" => SolidBoolean(parameters),
            "solid.create_primitive" => SolidCreatePrimitive(parameters),
            "solid.extrude" => SolidExtrude(parameters),
            "solid.rotate" => SolidRotate(parameters),
            "solid.sweep" => SolidSweep(parameters),
            "toolset.get_info" => ToolsetGetInfo(parameters),
            "topology.find_edges" => TopologyFindEdges(parameters),
            "topology.find_faces" => TopologyFindFaces(parameters),
            "topology.pick_face" => TopologyPickFace(parameters),
            "transform.move" => TransformMove(parameters),
            "transform.reflect" => TransformReflect(parameters),
            "transform.rotate" => TransformRotate(parameters),
            "transform.scale" => TransformScale(parameters),
            "undo.begin" => UndoBegin(parameters),
            "undo.cancel" => UndoCancel(parameters),
            "undo.end" => UndoEnd(parameters),
            "workspace.delete" => WorkspaceDelete(parameters),
            "workspace.name" => WorkspaceName(parameters),
            _ => throw new JsonRpcException(-32601, $"Method not found: {method}")
        };
    }

    // ----- Generated handlers (stubs) -----
    /// <summary>
    /// Commits one or more workspace objects into the document model (so they appear in the model tree and will be saved). Returns committed object ids.
    /// </summary>
    private JsonNode DocCommitObjects(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var objects = RequireProperty(p, "objects");

        DocCommitObjectsImpl(objects);

        var result = new JsonObject();
        result["committed"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Returns document state: active units (length), active selection, and current document version counter (monotonic).
    /// </summary>
    private JsonNode DocGetState(JsonElement root)
    {
        var p = RequireObject(root, "params");

        DocGetStateImpl();

        var result = new JsonObject();
        result["docVersion"] = null; // TODO
        result["lengthUnit"] = null; // TODO
        result["selection"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Rounds (fillets) the specified edges of a solid. Edges can be selected by ids, named sets, queries, or set expressions. Supports automatic topology rebind (default: rebind=true) after the operation so that named faces/edges remain usable across feature/boolean changes.
    /// </summary>
    private JsonNode FeatureFilletEdges(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var solid = RequireObjectRef<object>(p, "solid"); // maybe you need to change the <type> manually;
        var edges = RequireProperty(p, "edges");
        var radius = RequireProperty(p, "radius");
        var name = GetOptionalString(p, "name");
        var rebind = GetOptionalBool(p, "rebind", true);
        var rebindTargets = GetOptional(p, "rebindTargets");

        FeatureFilletEdgesImpl(solid, edges, radius, name, rebind, rebindTargets);

        var result = new JsonObject();
        result["feature"] = new JsonObject();
        result["feature"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["feature"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Creates a cylindrical hole on a planar face of a solid. centerOnFace uses face-local UV coordinates (0,0 is face origin). Optionally captures created topology outputs as named sets. Supports automatic topology rebind (default: rebind=true) after the operation so that named faces/edges remain usable across feature/boolean changes.
    /// </summary>
    private JsonNode FeatureHole(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var solid = RequireObjectRef<object>(p, "solid"); // maybe you need to change the <type> manually;
        var face = RequireObjectRef<object>(p, "face"); // maybe you need to change the <type> manually;
        var centerOnFace = GetOptional(p, "centerOnFace");
        var center = GetOptional(p, "center");
        var diameter = RequireProperty(p, "diameter");
        var through = GetOptionalBool(p, "through", true);
        var depth = GetOptional(p, "depth");
        var name = GetOptionalString(p, "name");
        var capture = GetOptional(p, "capture");
        var rebind = GetOptionalBool(p, "rebind", true);
        var rebindTargets = GetOptional(p, "rebindTargets");

        FeatureHoleImpl(solid, face, centerOnFace, center, diameter, through, depth, name, capture, rebind, rebindTargets);

        var result = new JsonObject();
        result["feature"] = new JsonObject();
        result["feature"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["feature"]!.AsObject()["name"] = name;
        result["outputs"] = new JsonObject();
        result["outputs"]!.AsObject()["entryEdges"] = new JsonArray();
        result["outputs"]!.AsObject()["exitEdges"] = new JsonArray();
        result["outputs"]!.AsObject()["wallFaces"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Creates a circular pattern of sketch entities around a 2D center point in sketch coordinates. If angle is omitted, a full 360° pattern is created. If merge=true, attempts to merge/boolean overlapping closed entities where applicable. If name is provided and nameWithSuffix=false, the name can refer to the whole result set; if nameWithSuffix=true, each created entity is named with a suffix.
    /// </summary>
    private JsonNode PatternCircularEntities(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var sketch = RequireObjectRef<Sketch>(p, "sketch"); // maybe you need to change the <type> manually;
        var entities = RequireProperty(p, "entities");
        var center = RequireProperty(p, "center");
        var count = RequireInteger(p, "count");
        var angle = GetOptional(p, "angle");
        var merge = GetOptionalBool(p, "merge", false);
        var name = GetOptionalString(p, "name");
        var nameWithSuffix = GetOptionalBool(p, "nameWithSuffix", false);

        PatternCircularEntitiesImpl(sketch, entities, center, count, angle, merge, name, nameWithSuffix);

        var result = new JsonObject();
        result["entities"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Creates a circular pattern of workspace objects (e.g., solids, curves, sketches) around a 3D axis passing through center. If angle is omitted, a full 360° pattern is created. If copy=false, keeps originals as the first instance and creates remaining as copies. If name is provided and nameWithSuffix=false, the name can refer to the whole result set; if nameWithSuffix=true, each created object is named with a suffix.
    /// </summary>
    private JsonNode PatternCircularObjects(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var objects = RequireProperty(p, "objects");
        var center = RequireProperty(p, "center");
        var axis = RequireProperty(p, "axis");
        var count = RequireInteger(p, "count");
        var angle = GetOptional(p, "angle");
        var copy = GetOptionalBool(p, "copy", true);
        var name = GetOptionalString(p, "name");
        var nameWithSuffix = GetOptionalBool(p, "nameWithSuffix", false);

        PatternCircularObjectsImpl(objects, center, axis, count, angle, copy, name, nameWithSuffix);

        var result = new JsonObject();
        result["objects"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Creates a rectangular/grid pattern of sketch entities. Step vectors are given in sketch plane coordinates (2D), allowing arbitrary directions (not limited to horizontal/vertical). If merge=true, attempts to merge/boolean overlapping closed entities where applicable. If name is provided and nameWithSuffix=false, the name can refer to the whole result set; if nameWithSuffix=true, each created entity is named with a suffix.
    /// </summary>
    private JsonNode PatternGridEntities(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var sketch = RequireObjectRef<Sketch>(p, "sketch"); // maybe you need to change the <type> manually;
        var entities = RequireProperty(p, "entities");
        var countX = RequireInteger(p, "countX");
        var countY = RequireInteger(p, "countY");
        var stepX = RequireProperty(p, "stepX");
        var stepY = RequireProperty(p, "stepY");
        var merge = GetOptionalBool(p, "merge", false);
        var name = GetOptionalString(p, "name");
        var nameWithSuffix = GetOptionalBool(p, "nameWithSuffix", false);

        PatternGridEntitiesImpl(sketch, entities, countX, countY, stepX, stepY, merge, name, nameWithSuffix);

        var result = new JsonObject();
        result["entities"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Creates a rectangular/grid pattern of workspace objects (e.g., solids, curves). Copies the given objects in a countX by countY grid using 3D step vectors. If copy=false, moves originals to the first position and creates remaining as copies (typical CAD behavior is copy=true). Returns created object references.
    /// </summary>
    private JsonNode PatternGridObjects(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var objects = RequireProperty(p, "objects");
        var countX = RequireInteger(p, "countX");
        var countY = RequireInteger(p, "countY");
        var stepX = RequireProperty(p, "stepX");
        var stepY = RequireProperty(p, "stepY");
        var copy = GetOptionalBool(p, "copy", true);
        var namePrefix = GetOptionalString(p, "namePrefix");

        PatternGridObjectsImpl(objects, countX, countY, stepX, stepY, copy, namePrefix);

        var result = new JsonObject();
        result["objects"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Generates points on a planar face by inset distances from its outer boundary bounding rectangle in face coordinates. Typical use: 4 corner hole centers with inset=10mm. Returns points in 3D.
    /// </summary>
    private JsonNode PatternInsetRectanglePoints(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var face = RequireObjectRef<object>(p, "face"); // maybe you need to change the <type> manually;
        var insetX = RequireProperty(p, "insetX");
        var insetY = RequireProperty(p, "insetY");
        var mode = GetOptionalString(p, "mode");

        PatternInsetRectanglePointsImpl(face, insetX, insetY, mode);

        var result = new JsonObject();
        result["points"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Adds a 2D entity to a sketch. All coordinates are in sketch (u,v) coordinates on the sketch plane. Entities must lie in the sketch plane; 3D points are not accepted here.
    /// </summary>
    private JsonNode SketchAddEntity(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var sketch = RequireObjectRef<Sketch>(p, "sketch"); // maybe you need to change the <type> manually;
        var kind = RequireString(p, "kind");
        var @params = RequireProperty(p, "params");
        var name = GetOptionalString(p, "name");

        SketchAddEntityImpl(sketch, kind, @params, name);

        return new JsonObject();
    }

    /// <summary>
    /// Performs a 2D boolean on sketch entities/regions and returns a new region object. Inputs are treated as closed planar regions in the sketch plane.
    /// </summary>
    private JsonNode SketchBoolean(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var sketch = RequireObjectRef<Sketch>(p, "sketch"); // maybe you need to change the <type> manually;
        var op = RequireString(p, "op");
        var inputs = RequireProperty(p, "inputs");
        var subtract = GetOptional(p, "subtract");
        var name = GetOptionalString(p, "name");

        SketchBooleanImpl(sketch, op, inputs, subtract, name);

        var result = new JsonObject();
        result["region"] = new JsonObject();
        result["region"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["region"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Connects open sketch entities into continuous chains/contours when endpoints match within precision. If entities is omitted, considers all eligible entities in the sketch. If closeGaps=true, remaining gaps are closed by inserting straight line segments (useful e.g. to close a 'C' shape made from two concentric arcs). If name is omitted, the operation overwrites the original entity/entities; if name is provided, the original remains and new connected entities are created.
    /// </summary>
    private JsonNode SketchConnect(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var sketch = RequireObjectRef<Sketch>(p, "sketch"); // maybe you need to change the <type> manually;
        var entities = GetOptional(p, "entities");
        var precision = RequireProperty(p, "precision");
        var closeGaps = GetOptionalBool(p, "closeGaps", false);
        var name = GetOptionalString(p, "name");

        SketchConnectImpl(sketch, entities, precision, closeGaps, name);

        var result = new JsonObject();
        result["entities"] = new JsonArray();
        result["affectedCount"] = null; // TODO
        result["contourCount"] = null; // TODO
        return result;
    }

    /// <summary>
    /// Creates a new sketch on a plane. Returns sketchId.
    /// </summary>
    private JsonNode SketchCreate(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var plane = RequireProperty(p, "plane");
        var name = GetOptionalString(p, "name");

        SketchCreateImpl(plane, name);

        var result = new JsonObject();
        result["sketch"] = new JsonObject();
        result["sketch"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["sketch"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Creates a new sketch attached to a planar face. Returns sketchId and the derived sketch plane.
    /// </summary>
    private JsonNode SketchCreateOnFace(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var face = RequireObjectRef<object>(p, "face"); // maybe you need to change the <type> manually;
        var name = GetOptionalString(p, "name");

        SketchCreateOnFaceImpl(face, name);

        var result = new JsonObject();
        result["sketch"] = new JsonObject();
        result["sketch"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["sketch"]!.AsObject()["name"] = name;
        result["plane"] = null; // TODO
        return result;
    }

    /// <summary>
    /// Rounds (fillets) vertices of sketch entities. If entity is omitted, applies to all eligible entities in the sketch. Vertex selection can be done by proximity points (2D) or by vertex indices (for entities with an ordered vertex list such as polycurve/rectangle/ngon). If neither points nor indices are provided, all vertices are rounded. If name is omitted, the operation overwrites the original entity (same name as the source). If name is provided, a new entity is created and the original remains.
    /// </summary>
    private JsonNode SketchRoundVertices(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var sketch = RequireObjectRef<Sketch>(p, "sketch"); // maybe you need to change the <type> manually;
        var entity = GetOptional(p, "entity");
        var radius = RequireProperty(p, "radius");
        var nearPoints = GetOptional(p, "nearPoints");
        var indices = GetOptional(p, "indices");
        var tolerance = GetOptional(p, "tolerance");
        var name = GetOptionalString(p, "name");

        SketchRoundVerticesImpl(sketch, entity, radius, nearPoints, indices, tolerance, name);

        var result = new JsonObject();
        result["entities"] = new JsonArray();
        result["affectedCount"] = null; // TODO
        return result;
    }

    /// <summary>
    /// Performs a boolean operation on solids. The first operand is the target (and defines the default name). The second operand can be a single solid or a list of solids. Does not modify inputs; returns a new solid. Supports automatic topology rebind (default: rebind=true) after the operation so that named faces/edges remain usable across boolean changes.
    /// </summary>
    private JsonNode SolidBoolean(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var op = RequireString(p, "op");
        var a = RequireObjectRef<object>(p, "a"); // maybe you need to change the <type> manually;
        var b = RequireProperty(p, "b");
        var name = GetOptionalString(p, "name");
        var rebind = GetOptionalBool(p, "rebind", true);
        var rebindTargets = GetOptional(p, "rebindTargets");

        SolidBooleanImpl(op, a, b, name, rebind, rebindTargets);

        var result = new JsonObject();
        result["solid"] = new JsonObject();
        result["solid"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["solid"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Creates a basic 3D primitive solid in the workspace. These primitives are often used as tools for boolean operations (e.g., to subtract a cone for a countersink). If name is provided, it is used to reference the created solid in subsequent operations, which is typically easier than using an auto-generated id.
    /// </summary>
    private JsonNode SolidCreatePrimitive(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var kind = RequireString(p, "kind");
        var @params = RequireProperty(p, "params");
        var name = GetOptionalString(p, "name");

        SolidCreatePrimitiveImpl(kind, @params, name);

        var result = new JsonObject();
        result["solid"] = new JsonObject();
        result["solid"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["solid"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Extrudes a profile into a new solid body. direction defaults to profile/sketch normal. The extrusion spans from offset to offset+length along direction. If pitch is provided, performs a helical (screw-like) extrusion around the axis. Returns the new solid. Optionally captures start/end faces and profile-edge loops as named sets.
    /// </summary>
    private JsonNode SolidExtrude(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var profile = RequireObjectRef<object>(p, "profile"); // maybe you need to change the <type> manually;
        var length = RequireProperty(p, "length");
        var direction = GetOptional(p, "direction");
        var name = GetOptionalString(p, "name");
        var offset = GetOptional(p, "offset");
        var pitch = GetOptional(p, "pitch");
        var capture = GetOptional(p, "capture");

        SolidExtrudeImpl(profile, length, direction, name, offset, pitch, capture);

        var result = new JsonObject();
        result["solid"] = new JsonObject();
        result["solid"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["solid"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Revolves a planar profile around an axis to create a new solid body (revolve). angle can be full rotation or degrees. Returns the new solid. For partial revolves, start/end cap faces may be captured.
    /// </summary>
    private JsonNode SolidRotate(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var profile = RequireObjectRef<object>(p, "profile"); // maybe you need to change the <type> manually;
        var axis = RequireProperty(p, "axis");
        var angle = RequireProperty(p, "angle");
        var name = GetOptionalString(p, "name");
        var capture = GetOptional(p, "capture");

        SolidRotateImpl(profile, axis, angle, name, capture);

        var result = new JsonObject();
        result["solid"] = new JsonObject();
        result["solid"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["solid"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Sweeps a profile along a path curve to create a new solid body. Path is a 3D curve or polycurve. Orientation defaults to 'follow' (Frenet/transport). Returns the new solid. Optionally captures start/end faces and profile-edge loops.
    /// </summary>
    private JsonNode SolidSweep(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var profile = RequireObjectRef<object>(p, "profile"); // maybe you need to change the <type> manually;
        var path = RequireObjectRef<object>(p, "path"); // maybe you need to change the <type> manually;
        var orientation = GetOptionalString(p, "orientation");
        var name = GetOptionalString(p, "name");
        var capture = GetOptional(p, "capture");

        SolidSweepImpl(profile, path, orientation, name, capture);

        var result = new JsonObject();
        result["solid"] = new JsonObject();
        result["solid"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["solid"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Returns information about the active MCP toolset definition loaded by the server.
    /// </summary>
    private JsonNode ToolsetGetInfo(JsonElement root)
    {
        var p = RequireObject(root, "params");

        ToolsetGetInfoImpl();

        var result = new JsonObject();
        result["toolsetId"] = null; // TODO
        result["toolsetVersion"] = null; // TODO
        result["schemaVersion"] = null; // TODO
        result["generatedAt"] = null; // TODO
        result["toolsHash"] = null; // TODO
        return result;
    }

    /// <summary>
    /// Finds edges on a solid by filter. Optionally captures the resulting edge list as a named set for later selection without ids.
    /// </summary>
    private JsonNode TopologyFindEdges(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var solid = RequireObjectRef<object>(p, "solid"); // maybe you need to change the <type> manually;
        var filter = GetOptional(p, "filter");
        var limit = GetOptionalInteger(p, "limit", 200);
        var name = GetOptionalString(p, "name");

        TopologyFindEdgesImpl(solid, filter, limit, name);

        var result = new JsonObject();
        result["edges"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Finds faces on a solid by filter. Optionally captures the resulting face list as a named set for later selection without ids.
    /// </summary>
    private JsonNode TopologyFindFaces(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var solid = RequireObjectRef<object>(p, "solid"); // maybe you need to change the <type> manually;
        var filter = RequireProperty(p, "filter");
        var limit = GetOptionalInteger(p, "limit", 20);
        var name = GetOptionalString(p, "name");

        TopologyFindFacesImpl(solid, filter, limit, name);

        var result = new JsonObject();
        result["faces"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Picks a face on a solid near a given point and matching an optional filter (surface type, approximate normal). Useful to disambiguate faces.
    /// </summary>
    private JsonNode TopologyPickFace(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var solid = RequireObjectRef<object>(p, "solid"); // maybe you need to change the <type> manually;
        var nearPoint = RequireProperty(p, "nearPoint");
        var filter = GetOptional(p, "filter");
        var name = GetOptionalString(p, "name");

        TopologyPickFaceImpl(solid, nearPoint, filter, name);

        var result = new JsonObject();
        result["face"] = new JsonObject();
        result["face"]!.AsObject()["id"] = GetNextId(name); // remove name when there is none
        result["face"]!.AsObject()["name"] = name;
        return result;
    }

    /// <summary>
    /// Translates one or more objects by a 3D vector. If copy=true, returns new objects; otherwise modifies originals. Returned objects are references to moved/copied objects. When copy=true, the server can also copy named topology references (copyNamed=true) and create new names using nameSuffix.
    /// </summary>
    private JsonNode TransformMove(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var objects = RequireProperty(p, "objects");
        var delta = RequireProperty(p, "delta");
        var copy = GetOptionalBool(p, "copy", false);
        var namePrefix = GetOptionalString(p, "namePrefix");
        var copyNamed = GetOptionalBool(p, "copyNamed", true);
        var nameSuffix = GetOptionalString(p, "nameSuffix");
        var nameConflict = GetOptionalString(p, "nameConflict");

        TransformMoveImpl(objects, delta, copy, namePrefix, copyNamed, nameSuffix, nameConflict);

        var result = new JsonObject();
        result["objects"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Reflects (mirrors) one or more objects across a plane. If copy=true, returns new objects; otherwise modifies originals. When copy=true, the server can also copy named topology references (copyNamed=true) and create new names using nameSuffix.
    /// </summary>
    private JsonNode TransformReflect(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var objects = RequireProperty(p, "objects");
        var plane = RequireProperty(p, "plane");
        var copy = GetOptionalBool(p, "copy", true);
        var namePrefix = GetOptionalString(p, "namePrefix");
        var copyNamed = GetOptionalBool(p, "copyNamed", true);
        var nameSuffix = GetOptionalString(p, "nameSuffix");
        var nameConflict = GetOptionalString(p, "nameConflict");

        TransformReflectImpl(objects, plane, copy, namePrefix, copyNamed, nameSuffix, nameConflict);

        var result = new JsonObject();
        result["objects"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Rotates one or more objects around an axis by a given angle. If copy=true, returns new objects; otherwise modifies originals. When copy=true, the server can also copy named topology references (copyNamed=true) and create new names using nameSuffix.
    /// </summary>
    private JsonNode TransformRotate(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var objects = RequireProperty(p, "objects");
        var axis = RequireProperty(p, "axis");
        var angle = RequireProperty(p, "angle");
        var copy = GetOptionalBool(p, "copy", false);
        var namePrefix = GetOptionalString(p, "namePrefix");
        var copyNamed = GetOptionalBool(p, "copyNamed", true);
        var nameSuffix = GetOptionalString(p, "nameSuffix");
        var nameConflict = GetOptionalString(p, "nameConflict");

        TransformRotateImpl(objects, axis, angle, copy, namePrefix, copyNamed, nameSuffix, nameConflict);

        var result = new JsonObject();
        result["objects"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Scales one or more objects about an origin. Provide either uniform factor or non-uniform factors (x,y,z). If copy=true, returns new objects; otherwise modifies originals. When copy=true, the server can also copy named topology references (copyNamed=true) and create new names using nameSuffix.
    /// </summary>
    private JsonNode TransformScale(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var objects = RequireProperty(p, "objects");
        var origin = RequireProperty(p, "origin");
        var factor = GetOptional(p, "factor");
        var factors = GetOptional(p, "factors");
        var copy = GetOptionalBool(p, "copy", false);
        var namePrefix = GetOptionalString(p, "namePrefix");
        var copyNamed = GetOptionalBool(p, "copyNamed", true);
        var nameSuffix = GetOptionalString(p, "nameSuffix");
        var nameConflict = GetOptionalString(p, "nameConflict");

        TransformScaleImpl(objects, origin, factor, factors, copy, namePrefix, copyNamed, nameSuffix, nameConflict);

        var result = new JsonObject();
        result["objects"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Begins an undo frame. All subsequent committed changes until undo.end are grouped into one undo step. Returns undoFrameId.
    /// </summary>
    private JsonNode UndoBegin(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var label = RequireString(p, "label");

        UndoBeginImpl(label);

        var result = new JsonObject();
        result["undoFrameId"] = null; // TODO
        return result;
    }

    /// <summary>
    /// Cancels an undo frame started with undo.begin, rolling back all changes in that frame.
    /// </summary>
    private JsonNode UndoCancel(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var undoFrameId = RequireString(p, "undoFrameId");

        UndoCancelImpl(undoFrameId);

        return new JsonObject();
    }

    /// <summary>
    /// Ends an undo frame started with undo.begin. If errors occurred, server may auto-cancel the frame.
    /// </summary>
    private JsonNode UndoEnd(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var undoFrameId = RequireString(p, "undoFrameId");

        UndoEndImpl(undoFrameId);

        return new JsonObject();
    }

    /// <summary>
    /// Deletes one or more workspace objects (temporary objects not yet committed). Deleting a committed object is not allowed and returns E_INVALID_PARAMS.
    /// </summary>
    private JsonNode WorkspaceDelete(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var objects = RequireProperty(p, "objects");

        WorkspaceDeleteImpl(objects);

        return new JsonObject();
    }

    /// <summary>
    /// Defines or updates a named value (number, point, vector) in the current workspace context. Used for expressions. Returns the canonical name.
    /// </summary>
    private JsonNode WorkspaceName(JsonElement root)
    {
        var p = RequireObject(root, "params");
        var name = RequireString(p, "name");
        var value = RequireProperty(p, "value");

        WorkspaceNameImpl(name, value);

        var result = new JsonObject();
        result["name"] = name;
        return result;
    }

}

