// <auto-generated>
// Generated from: McpToolsetDefinition.json
// Generated at:  2026-05-06T10:08:18.5358225+02:00
// </auto-generated>

using System;
using System.Text.Json;
using System.Text.Json.Nodes;
using CADability;

namespace ShapeIt;

public partial class MCPServer
{
    // You are expected to provide these helpers somewhere in your server code:
    // - JsonElement RequireObject(JsonElement root, string propName)
    // - JsonElement RequireProperty(JsonElement obj, string propName)
    // - string RequireString(JsonElement obj, string propName)
    // - JsonElement? GetOptional(JsonElement obj, string propName)
    // - string? GetOptionalString(JsonElement obj, string propName)
    // - T RequireObjectRef<T>(JsonElement obj, string propName) where T : class
    // - void ValidateEnum(string value, params string[] allowed)

    // ----- Dispatcher snippet -----
    // Paste into your ProcessMethod switch(method) and adapt to your class:
    public JsonNode DispatchGenerated(string method, JsonElement parameters)
    {
        return method switch
        {
            "assert.check" => AssertCheck(parameters),
            "document.commit_objects" => DocumentCommitObjects(parameters),
            "document.get_state" => DocumentGetState(parameters),
            "document.update_objects" => DocumentUpdateObjects(parameters),
            "feature.chamfer" => FeatureChamfer(parameters),
            "feature.fillet" => FeatureFillet(parameters),
            "feature.hole" => FeatureHole(parameters),
            "feature.split" => FeatureSplit(parameters),
            "inspect.properties" => InspectProperties(parameters),
            "inspect.scene" => InspectScene(parameters),
            "inspect.summary" => InspectSummary(parameters),
            "pattern.by_formula_solids" => PatternByFormulaSolids(parameters),
            "pattern.circular_sketch" => PatternCircularSketch(parameters),
            "pattern.circular_solids" => PatternCircularSolids(parameters),
            "pattern.grid_sketch" => PatternGridSketch(parameters),
            "pattern.grid_solids" => PatternGridSolids(parameters),
            "sketch.add_arc" => SketchAddArc(parameters),
            "sketch.add_circle" => SketchAddCircle(parameters),
            "sketch.add_circle_by_constraints" => SketchAddCircleByConstraints(parameters),
            "sketch.add_ellipse" => SketchAddEllipse(parameters),
            "sketch.add_ellipse_arc" => SketchAddEllipseArc(parameters),
            "sketch.add_line" => SketchAddLine(parameters),
            "sketch.add_line_by_constraints" => SketchAddLineByConstraints(parameters),
            "sketch.add_nurbs" => SketchAddNurbs(parameters),
            "sketch.add_polycurve" => SketchAddPolycurve(parameters),
            "sketch.add_rectangle" => SketchAddRectangle(parameters),
            "sketch.add_regular_polygon" => SketchAddRegularPolygon(parameters),
            "sketch.add_slot" => SketchAddSlot(parameters),
            "sketch.add_solid_section" => SketchAddSolidSection(parameters),
            "sketch.add_text" => SketchAddText(parameters),
            "sketch.angle_bisector" => SketchAngleBisector(parameters),
            "sketch.boolean" => SketchBoolean(parameters),
            "sketch.connect" => SketchConnect(parameters),
            "sketch.create" => SketchCreate(parameters),
            "sketch.create_on_face" => SketchCreateOnFace(parameters),
            "sketch.foot_point_on_curve" => SketchFootPointOnCurve(parameters),
            "sketch.get_vertices" => SketchGetVertices(parameters),
            "sketch.intersections" => SketchIntersections(parameters),
            "sketch.offset" => SketchOffset(parameters),
            "sketch.perpendicular_through" => SketchPerpendicularThrough(parameters),
            "sketch.round_vertices" => SketchRoundVertices(parameters),
            "sketch.set_curve_endpoints" => SketchSetCurveEndpoints(parameters),
            "solid.boolean" => SolidBoolean(parameters),
            "solid.box" => SolidBox(parameters),
            "solid.capsule" => SolidCapsule(parameters),
            "solid.cone" => SolidCone(parameters),
            "solid.cylinder" => SolidCylinder(parameters),
            "solid.extrude" => SolidExtrude(parameters),
            "solid.helical_extrude" => SolidHelicalExtrude(parameters),
            "solid.pipe" => SolidPipe(parameters),
            "solid.rotate" => SolidRotate(parameters),
            "solid.ruled" => SolidRuled(parameters),
            "solid.sphere" => SolidSphere(parameters),
            "solid.sweep" => SolidSweep(parameters),
            "solid.torus" => SolidTorus(parameters),
            "surface.parametric" => SurfaceParametric(parameters),
            "system.get_info" => SystemGetInfo(parameters),
            "template.begin" => TemplateBegin(parameters),
            "template.commit" => TemplateCommit(parameters),
            "template.instantiate" => TemplateInstantiate(parameters),
            "transform.move" => TransformMove(parameters),
            "transform.reflect" => TransformReflect(parameters),
            "transform.rotate" => TransformRotate(parameters),
            "transform.scale" => TransformScale(parameters),
            "undo.begin" => UndoBegin(parameters),
            "undo.cancel" => UndoCancel(parameters),
            "undo.end" => UndoEnd(parameters),
            "workspace.delete" => WorkspaceDelete(parameters),
            "workspace.set" => WorkspaceSet(parameters),
            _ => throw new JsonRpcException(-32601, $"Method not found: {method}")
        };
    }

    // ----- Generated handlers (stubs) -----
    /// <summary>
    /// Checks a global boolean expression or validates a condition for all objects selected by a selector/query. If the check fails, the batch stops with an error.
    /// </summary>
    private JsonNode AssertCheck(JsonElement root)
    {
        AssertIsObject(root);
        var objects = GetOptional(root, "objects");
        var condition = GetOptionalString(root, "condition");
        var minCount = GetOptionalInteger(root, "minCount", -1);
        var maxCount = GetOptionalInteger(root, "maxCount", -1);
        var message = GetOptionalString(root, "message");
        var name = GetOptionalString(root, "name");

        AssertCheckImpl(objects, condition, minCount, maxCount, message, name);

        return default;
    }

    /// <summary>
    /// Commits one or more workspace objects into the document model (so they appear in the model tree and will be saved). Returns committed object ids. Note: objects are resolved via Selector (may select one or many).
    /// </summary>
    private JsonNode DocumentCommitObjects(JsonElement root)
    {
        AssertIsObject(root);
        var objects = RequireProperty(root, "objects");

        DocumentCommitObjectsImpl(objects);

        return default;
    }

    /// <summary>
    /// Returns document state: active units (length), active selection, and current document version counter (monotonic).
    /// </summary>
    private JsonNode DocumentGetState(JsonElement root)
    {
        AssertIsObject(root);

        DocumentGetStateImpl();

        var result = new JsonObject();
        result["docVersion"] = null; // TODO
        result["lengthUnit"] = null; // TODO
        result["selection"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Updates the document model by removing existing committed objects and adding new workspace objects in a single operation. Both 'remove' and 'add' accept selectors and may reference one or many objects. This operation is typically used in iterative modeling workflows where a previously committed result is replaced by an improved version.
    /// </summary>
    private JsonNode DocumentUpdateObjects(JsonElement root)
    {
        AssertIsObject(root);
        var remove = GetOptional(root, "remove");
        var add = GetOptional(root, "add");

        DocumentUpdateObjectsImpl(remove, add);

        return default;
    }

    /// <summary>
    /// Chamfers the specified edges of a solid. Edges can be selected by named sets, queries, or set expressions. Supports automatic topology rebind (default: rebind=true) after the operation so that named faces/edges remain usable across feature/boolean changes. For an unsymmetric chamfer you must provide 'primaryFace' and 'secondaryDistance'
    /// </summary>
    private JsonNode FeatureChamfer(JsonElement root)
    {
        AssertIsObject(root);
        var solid = RequireProperty(root, "solid");
        var edges = RequireProperty(root, "edges");
        var distance = RequireDouble(root, "distance");
        var primaryFace = GetOptional(root, "primaryFace");
        var secondaryDistance = GetOptionalDouble(root, "secondaryDistance", double.NaN);
        var name = GetOptionalString(root, "name");
        var rebind = GetOptionalBool(root, "rebind", true);
        var rebindTargets = GetOptional(root, "rebindTargets");

        FeatureChamferImpl(solid, edges, distance, primaryFace, secondaryDistance, name, rebind, rebindTargets);

        return default;
    }

    /// <summary>
    /// Rounds (fillets) the specified edges of a solid. Edges can be selected by ids, named sets, queries, or set expressions. Supports automatic topology rebind (default: rebind=true) after the operation so that named faces/edges remain usable across feature/boolean changes.
    /// </summary>
    private JsonNode FeatureFillet(JsonElement root)
    {
        AssertIsObject(root);
        var solid = RequireProperty(root, "solid");
        var edges = RequireProperty(root, "edges");
        var radius = RequireDouble(root, "radius");
        var name = GetOptionalString(root, "name");
        var rebind = GetOptionalBool(root, "rebind", true);
        var rebindTargets = GetOptional(root, "rebindTargets");

        FeatureFilletImpl(solid, edges, radius, name, rebind, rebindTargets);

        return default;
    }

    /// <summary>
    /// Creates a cylindrical hole on a planar face of a solid. centerOnFace uses face-local UV coordinates (0,0 is face origin). Optionally captures created topology outputs as named sets. Supports automatic topology rebind (default: rebind=true) after the operation so that named faces/edges remain usable across feature/boolean changes. Note: solid is resolved via Selector (expected single solid). Note: face is resolved via Selector (expected single face).
    /// </summary>
    private JsonNode FeatureHole(JsonElement root)
    {
        AssertIsObject(root);
        var solid = RequireProperty(root, "solid");
        var face = RequireProperty(root, "face");
        var centerOnFace = GetOptional(root, "centerOnFace");
        var center = GetOptionalPoint3D(root, "center", GeoPoint.Invalid);
        var diameter = RequireDouble(root, "diameter");
        var through = GetOptionalBool(root, "through", true);
        var depth = GetOptionalDouble(root, "depth", double.NaN);
        var name = GetOptionalString(root, "name");
        var capture = GetOptional(root, "capture");
        var rebind = GetOptionalBool(root, "rebind", true);
        var rebindTargets = GetOptional(root, "rebindTargets");

        FeatureHoleImpl(solid, face, centerOnFace, center, diameter, through, depth, name, capture, rebind, rebindTargets);

        return default;
    }

    /// <summary>
    /// Split a solid by a separating surface. Currently, splitBy is a plane. The selected solid is divided into parts on the two sides of the plane. Parts on the side pointed to by the plane normal are considered outer; parts on the opposite side are considered inner. Result solids are only created for the sides for which a target name is provided. This allows efficient batch processing when only one side of the split is needed. Note: solid is resolved via Selector and must identify exactly one solid.
    /// </summary>
    private JsonNode FeatureSplit(JsonElement root)
    {
        AssertIsObject(root);
        var solid = RequireProperty(root, "solid");
        var splitBy = RequireProperty(root, "splitBy");
        var nameInner = GetOptionalString(root, "nameInner");
        var nameOuter = GetOptionalString(root, "nameOuter");
        var rebind = GetOptionalBool(root, "rebind", true);
        var rebindTargets = GetOptional(root, "rebindTargets");

        FeatureSplitImpl(solid, splitBy, nameInner, nameOuter, rebind, rebindTargets);

        return default;
    }

    /// <summary>
    /// Returns selected properties of a workspace object. Property names follow the same naming conventions used in expressions (e.g. 'boundingBox', 'boundingBox.width', 'volume').
    /// </summary>
    private JsonNode InspectProperties(JsonElement root)
    {
        AssertIsObject(root);
        var target = RequireString(root, "target");
        var properties = RequireProperty(root, "properties");

        InspectPropertiesImpl(target, properties);

        var result = new JsonObject();
        result["values"] = new JsonObject();
        return result;
    }

    /// <summary>
    /// Returns a spatial description of multiple workspace objects so their relative positions can be analyzed. Optionally includes geometry representations such as bounding boxes or mesh data.
    /// </summary>
    private JsonNode InspectScene(JsonElement root)
    {
        AssertIsObject(root);
        var targets = RequireProperty(root, "targets");
        var includeBoundingBoxes = GetOptionalBool(root, "includeBoundingBoxes", true);
        var geometryFormat = GetOptionalString(root, "geometryFormat");
        var includeImage = GetOptionalBool(root, "includeImage", false);

        InspectSceneImpl(targets, includeBoundingBoxes, geometryFormat, includeImage);

        var result = new JsonObject();
        result["objects"] = new JsonArray();
        result["sceneBoundingBox"] = new JsonObject();
        result["image"] = null; // TODO
        return result;
    }

    /// <summary>
    /// Returns a concise summary of one or more workspace objects. The summary includes the object type and basic properties such as value, bounding box, or element counts when applicable.
    /// </summary>
    private JsonNode InspectSummary(JsonElement root)
    {
        AssertIsObject(root);
        var targets = RequireProperty(root, "targets");

        InspectSummaryImpl(targets);

        var result = new JsonObject();
        result["objects"] = new JsonArray();
        return result;
    }

    /// <summary>
    /// Creates a formula-driven pattern of solid instances. The source can be existing solids or a parametric template. One or more loop variables are evaluated, optional helper formulas are computed, an optional condition is evaluated for the current iteration, then a transform expression and optional template arguments are applied per instance.
    /// </summary>
    private JsonNode PatternByFormulaSolids(JsonElement root)
    {
        AssertIsObject(root);
        var solids = GetOptional(root, "solids");
        var template = GetOptionalString(root, "template");
        var variables = RequireProperty(root, "variables");
        var formulas = GetOptional(root, "formulas");
        var condition = GetOptionalString(root, "condition");
        var arguments = GetOptional(root, "arguments");
        var transform = RequireString(root, "transform");
        var includeSource = GetOptionalBool(root, "includeSource", false);
        var copy = GetOptionalBool(root, "copy", true);
        var name = GetOptionalString(root, "name");
        var suffix = GetOptionalBool(root, "suffix", true);
        var indexName = GetOptionalString(root, "indexName");
        var skipInvalidInstances = GetOptionalBool(root, "skipInvalidInstances", false);

        PatternByFormulaSolidsImpl(solids, template, variables, formulas, condition, arguments, transform, includeSource, copy, name, suffix, indexName, skipInvalidInstances);

        return default;
    }

    /// <summary>
    /// Creates a circular pattern of sketch geometry around a 2D center point in sketch coordinates. If angle is omitted, a full 360° pattern is created. If merge=true, attempts to merge/boolean overlapping closed sketch geometry where applicable. If name is provided and nameWithSuffix=false, the name can refer to the whole result set; if nameWithSuffix=true, each created entity is named with a suffix.
    /// </summary>
    private JsonNode PatternCircularSketch(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var sketchGeometry = RequireProperty(root, "sketchGeometry");
        var center = RequirePoint2D(root, "center");
        var count = RequireInteger(root, "count");
        var angle = GetOptionalDouble(root, "angle", double.NaN);
        var merge = GetOptionalBool(root, "merge", false);
        var name = GetOptionalString(root, "name");
        var nameWithSuffix = GetOptionalBool(root, "nameWithSuffix", false);

        PatternCircularSketchImpl(sketch, sketchGeometry, center, count, angle, merge, name, nameWithSuffix);

        return default;
    }

    /// <summary>
    /// Creates a circular pattern of solids around a 3D axis passing through center. If angle is omitted, defaults to 360 degrees. If name is provided, it refers to the whole resulting set. If suffix is true, individual solids are also named using &lt;base&gt;_&lt;n&gt; where &lt;base&gt; is name (if provided) or the source object's name.
    /// </summary>
    private JsonNode PatternCircularSolids(JsonElement root)
    {
        AssertIsObject(root);
        var solids = RequireProperty(root, "solids");
        var axis = RequireAxis3D(root, "axis");
        var count = RequireInteger(root, "count");
        var angle = GetOptionalDouble(root, "angle", 360);
        var copy = GetOptionalBool(root, "copy", true);
        var name = GetOptionalString(root, "name");
        var suffix = GetOptionalBool(root, "suffix", false);

        PatternCircularSolidsImpl(solids, axis, count, angle, copy, name, suffix);

        return default;
    }

    /// <summary>
    /// Creates a rectangular/grid pattern of sketch geometry. Step vectors are given in sketch plane coordinates (2D), allowing arbitrary directions (not limited to horizontal/vertical). If merge=true, attempts to merge/boolean overlapping closed sketch geometry where applicable. If name is provided and nameWithSuffix=false, the name can refer to the whole result set; if nameWithSuffix=true, each created entity is named with a suffix.
    /// </summary>
    private JsonNode PatternGridSketch(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var sketchGeometry = RequireProperty(root, "sketchGeometry");
        var countX = RequireInteger(root, "countX");
        var countY = RequireInteger(root, "countY");
        var stepX = RequireProperty(root, "stepX");
        var stepY = RequireProperty(root, "stepY");
        var merge = GetOptionalBool(root, "merge", false);
        var name = GetOptionalString(root, "name");
        var nameWithSuffix = GetOptionalBool(root, "nameWithSuffix", false);

        PatternGridSketchImpl(sketch, sketchGeometry, countX, countY, stepX, stepY, merge, name, nameWithSuffix);

        return default;
    }

    /// <summary>
    /// Creates a rectangular or linear grid pattern of solids using 3D step vectors. If 'name' is provided, it refers to the entire resulting set. If 'suffix' is true, individual solids are also named using &lt;base&gt;_&lt;nx&gt;_&lt;ny&gt; (or &lt;base&gt;_&lt;n&gt; if one dimension equals 1), where &lt;base&gt; is 'name' (if provided) or the source object's name.
    /// </summary>
    private JsonNode PatternGridSolids(JsonElement root)
    {
        AssertIsObject(root);
        var solids = RequireProperty(root, "solids");
        var countX = RequireInteger(root, "countX");
        var countY = GetOptionalInteger(root, "countY", 0);
        var countXNegative = GetOptionalInteger(root, "countXNegative", 0);
        var countYNegative = GetOptionalInteger(root, "countYNegative", 0);
        var stepX = RequireVector3D(root, "stepX");
        var stepY = GetOptionalVector3D(root, "stepY", GeoVector.Invalid);
        var copy = GetOptionalBool(root, "copy", true);
        var name = GetOptionalString(root, "name");
        var suffix = GetOptionalBool(root, "suffix", false);

        PatternGridSolidsImpl(solids, countX, countY, countXNegative, countYNegative, stepX, stepY, copy, name, suffix);

        return default;
    }

    /// <summary>
    /// Adds an arc entity to a sketch.
    /// </summary>
    private JsonNode SketchAddArc(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var center = GetOptionalPoint2D(root, "center", GeoPoint2D.Invalid);
        var radius = GetOptionalDouble(root, "radius", double.NaN);
        var startAngle = GetOptionalDouble(root, "startAngle", double.NaN);
        var sweepAngle = GetOptionalDouble(root, "sweepAngle", double.NaN);
        var start = GetOptionalPoint2D(root, "start", GeoPoint2D.Invalid);
        var end = GetOptionalPoint2D(root, "end", GeoPoint2D.Invalid);
        var middle = GetOptionalPoint2D(root, "middle", GeoPoint2D.Invalid);
        var ccw = GetOptionalBool(root, "ccw", false);
        var name = GetOptionalString(root, "name");

        SketchAddArcImpl(sketch, center, radius, startAngle, sweepAngle, start, end, middle, ccw, name);

        return default;
    }

    /// <summary>
    /// Adds a circle entity to a sketch.
    /// </summary>
    private JsonNode SketchAddCircle(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var center = GetOptionalPoint2D(root, "center", GeoPoint2D.Invalid);
        var radius = GetOptionalDouble(root, "radius", double.NaN);
        var diameter = GetOptionalDouble(root, "diameter", double.NaN);
        var name = GetOptionalString(root, "name");

        SketchAddCircleImpl(sketch, center, radius, diameter, name);

        return default;
    }

    /// <summary>
    /// Constructs a full circle in a sketch from geometric constraints. Supported modes are: TTT (three constraints), TTR (two constraints plus radius), and TC (one constraint plus explicit center). Each constraint can be either a 2D point, meaning the circle must pass through that point, or a reference to existing sketch geometry, meaning the circle must be tangent to that geometry. If multiple valid solutions exist, the solution whose center is closest to preferredCenter is chosen.
    /// </summary>
    private JsonNode SketchAddCircleByConstraints(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var constraints = RequireProperty(root, "constraints");
        var radius = GetOptionalDouble(root, "radius", double.NaN);
        var center = GetOptionalPoint2D(root, "center", GeoPoint2D.Invalid);
        var preferredCenter = GetOptionalPoint2D(root, "preferredCenter", GeoPoint2D.Invalid);
        var tolerance = GetOptionalDouble(root, "tolerance", double.NaN);
        var name = GetOptionalString(root, "name");
        var capture = GetOptional(root, "capture");

        SketchAddCircleByConstraintsImpl(sketch, constraints, radius, center, preferredCenter, tolerance, name, capture);

        return default;
    }

    /// <summary>
    /// Adds an ellipse entity to a sketch.
    /// </summary>
    private JsonNode SketchAddEllipse(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var center = GetOptionalPoint2D(root, "center", GeoPoint2D.Invalid);
        var radiusMajor = GetOptionalDouble(root, "radiusMajor", double.NaN);
        var radiusMinor = GetOptionalDouble(root, "radiusMinor", double.NaN);
        var rotationDeg = GetOptionalDouble(root, "rotationDeg", 0);
        var name = GetOptionalString(root, "name");

        SketchAddEllipseImpl(sketch, center, radiusMajor, radiusMinor, rotationDeg, name);

        return default;
    }

    /// <summary>
    /// Adds an elliptical arc entity to a sketch.
    /// </summary>
    private JsonNode SketchAddEllipseArc(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var center = GetOptionalPoint2D(root, "center", GeoPoint2D.Invalid);
        var radiusMajor = RequireDouble(root, "radiusMajor");
        var radiusMinor = RequireDouble(root, "radiusMinor");
        var rotationDeg = GetOptionalDouble(root, "rotationDeg", 0);
        var startAngle = RequireDouble(root, "startAngle");
        var sweepAngle = RequireDouble(root, "sweepAngle");
        var name = GetOptionalString(root, "name");

        SketchAddEllipseArcImpl(sketch, center, radiusMajor, radiusMinor, rotationDeg, startAngle, sweepAngle, name);

        return default;
    }

    /// <summary>
    /// Adds a line entity to a sketch.
    /// </summary>
    private JsonNode SketchAddLine(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var start = RequirePoint2D(root, "start");
        var end = RequirePoint2D(root, "end");
        var name = GetOptionalString(root, "name");

        SketchAddLineImpl(sketch, start, end, name);

        return default;
    }

    /// <summary>
    /// Adds a line constructed from geometric constraints. Supported modes are: PT (start point plus tangency to one circle or arc) and TT (tangency to two circles or arcs). If multiple valid solutions exist, preferredStart and preferredEnd are used to choose the solution whose line endpoints are closest to those hints.
    /// </summary>
    private JsonNode SketchAddLineByConstraints(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var start = GetOptionalPoint2D(root, "start", GeoPoint2D.Invalid);
        var target0 = RequireProperty(root, "target0");
        var target1 = GetOptional(root, "target1");
        var preferredStart = GetOptionalPoint2D(root, "preferredStart", GeoPoint2D.Invalid);
        var preferredEnd = GetOptionalPoint2D(root, "preferredEnd", GeoPoint2D.Invalid);
        var tolerance = GetOptionalDouble(root, "tolerance", double.NaN);
        var name = GetOptionalString(root, "name");

        SketchAddLineByConstraintsImpl(sketch, start, target0, target1, preferredStart, preferredEnd, tolerance, name);

        return default;
    }

    /// <summary>
    /// Adds a NURBS curve to a sketch.
    /// </summary>
    private JsonNode SketchAddNurbs(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var degree = GetOptionalInteger(root, "degree", 3);
        var controlPoints = GetOptional(root, "controlPoints");
        var throughPoints = GetOptional(root, "throughPoints");
        var knots = GetOptional(root, "knots");
        var weights = GetOptional(root, "weights");
        var isPeriodic = GetOptionalBool(root, "isPeriodic", false);
        var approximation = GetOptional(root, "approximation");
        var name = GetOptionalString(root, "name");

        SketchAddNurbsImpl(sketch, degree, controlPoints, throughPoints, knots, weights, isPeriodic, approximation, name);

        return default;
    }

    /// <summary>
    /// Adds a polycurve entity to a sketch.
    /// </summary>
    private JsonNode SketchAddPolycurve(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var vertices = GetOptional(root, "vertices");
        var isClosed = GetOptionalBool(root, "isClosed", false);
        var name = GetOptionalString(root, "name");

        SketchAddPolycurveImpl(sketch, vertices, isClosed, name);

        return default;
    }

    /// <summary>
    /// Adds a rectangle entity to a sketch.
    /// </summary>
    private JsonNode SketchAddRectangle(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var width = RequireDouble(root, "width");
        var height = RequireDouble(root, "height");
        var cornerRadius = GetOptionalDouble(root, "cornerRadius", 0);
        var center = RequirePoint2D(root, "center");
        var rotationDeg = GetOptionalDouble(root, "rotationDeg", 0);
        var name = GetOptionalString(root, "name");

        SketchAddRectangleImpl(sketch, width, height, cornerRadius, center, rotationDeg, name);

        return default;
    }

    /// <summary>
    /// Adds a regular polygon entity to a sketch.
    /// </summary>
    private JsonNode SketchAddRegularPolygon(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var center = GetOptionalPoint2D(root, "center", GeoPoint2D.Invalid);
        var innerRadius = GetOptionalDouble(root, "innerRadius", double.NaN);
        var outerRadius = GetOptionalDouble(root, "outerRadius", double.NaN);
        var sides = GetOptionalInteger(root, "sides", 0);
        var rotationDeg = GetOptionalDouble(root, "rotationDeg", 0);
        var name = GetOptionalString(root, "name");

        SketchAddRegularPolygonImpl(sketch, center, innerRadius, outerRadius, sides, rotationDeg, name);

        return default;
    }

    /// <summary>
    /// Adds a slot entity to a sketch.
    /// </summary>
    private JsonNode SketchAddSlot(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var center = GetOptionalPoint2D(root, "center", GeoPoint2D.Invalid);
        var length = GetOptionalDouble(root, "length", double.NaN);
        var width = GetOptionalDouble(root, "width", double.NaN);
        var rotationDeg = GetOptionalDouble(root, "rotationDeg", double.NaN);
        var name = GetOptionalString(root, "name");

        SketchAddSlotImpl(sketch, center, length, width, rotationDeg, name);

        return default;
    }

    /// <summary>
    /// Intersects one or more solids with the plane of the specified sketch and adds the resulting section contours as closed profile geometry to that sketch. If the section produces multiple disconnected closed contours, all of them are added. If 'name' is provided, it refers to the whole resulting set of profiles.
    /// </summary>
    private JsonNode SketchAddSolidSection(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var solid = RequireProperty(root, "solid");
        var merge = GetOptionalBool(root, "merge", true);
        var name = GetOptionalString(root, "name");

        SketchAddSolidSectionImpl(sketch, solid, merge, name);

        return default;
    }

    /// <summary>
    /// Adds text to a sketch and converts it to sketch geometry as closed outline contours, including inner islands where present. The text is placed in sketch coordinates and is always oriented horizontally along the sketch x-axis.
    /// </summary>
    private JsonNode SketchAddText(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var text = RequireString(root, "text");
        var location = RequirePoint2D(root, "location");
        var height = RequireDouble(root, "height");
        var font = RequireProperty(root, "font");
        var horizontalAlign = GetOptional(root, "horizontalAlign");
        var verticalAlign = GetOptional(root, "verticalAlign");
        var characterSpacing = GetOptionalDouble(root, "characterSpacing", double.NaN);
        var wordSpacing = GetOptionalDouble(root, "wordSpacing", double.NaN);
        var name = GetOptionalString(root, "name");

        SketchAddTextImpl(sketch, text, location, height, font, horizontalAlign, verticalAlign, characterSpacing, wordSpacing, name);

        return default;
    }

    /// <summary>
    /// Creates an angle bisector line between two intersecting lines in a sketch.
    /// </summary>
    private JsonNode SketchAngleBisector(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var a = RequireProperty(root, "a");
        var b = RequireProperty(root, "b");
        var which = GetOptionalString(root, "which");
        var at = GetOptionalPoint2D(root, "at", GeoPoint2D.Invalid);
        var length = GetOptionalDouble(root, "length", 1);
        var name = GetOptionalString(root, "name");

        SketchAngleBisectorImpl(sketch, a, b, which, at, length, name);

        return default;
    }

    /// <summary>
    /// Performs a 2D boolean on sketch entities/regions and returns a new region object. Inputs are treated as closed planar regions in the sketch plane.
    /// </summary>
    private JsonNode SketchBoolean(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var op = RequireString(root, "op");
        var inputs = RequireProperty(root, "inputs");
        var subtract = GetOptional(root, "subtract");
        var name = GetOptionalString(root, "name");

        SketchBooleanImpl(sketch, op, inputs, subtract, name);

        return default;
    }

    /// <summary>
    /// Connects open sketch entities into continuous chains/contours when endpoints match within precision. If entities is omitted, considers all eligible entities in the sketch. If closeGaps=true, remaining gaps are closed by inserting straight line segments (useful e.g. to close a 'C' shape made from two concentric arcs). If name is omitted, the operation overwrites the original entity/entities; if name is provided, the original remains and new connected entities are created.
    /// </summary>
    private JsonNode SketchConnect(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var sketchGeometry = GetOptional(root, "sketchGeometry");
        var precision = RequireDouble(root, "precision");
        var closeGaps = GetOptionalBool(root, "closeGaps", false);
        var name = GetOptionalString(root, "name");

        SketchConnectImpl(sketch, sketchGeometry, precision, closeGaps, name);

        return default;
    }

    /// <summary>
    /// Creates a new sketch on a plane. Returns sketchId.
    /// </summary>
    private JsonNode SketchCreate(JsonElement root)
    {
        AssertIsObject(root);
        var plane = RequirePlane(root, "plane");
        var name = GetOptionalString(root, "name");

        SketchCreateImpl(plane, name);

        return default;
    }

    /// <summary>
    /// Creates a new sketch attached to a planar face. Returns sketchId and the derived sketch plane. Note: face is resolved via Selector (expected single face).
    /// </summary>
    private JsonNode SketchCreateOnFace(JsonElement root)
    {
        AssertIsObject(root);
        var face = RequireProperty(root, "face");
        var point = GetOptionalPoint3D(root, "point", GeoPoint.Invalid);
        var xAxis = GetOptionalVector3D(root, "xAxis", GeoVector.Invalid);
        var name = GetOptionalString(root, "name");

        SketchCreateOnFaceImpl(face, point, xAxis, name);

        return default;
    }

    /// <summary>
    /// Computes the closest orthogonal foot point of a given point onto a curve in a sketch.
    /// </summary>
    private JsonNode SketchFootPointOnCurve(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var point = RequirePoint2D(root, "point");
        var curve = RequireProperty(root, "curve");
        var mode = GetOptionalString(root, "mode");
        var clamp = GetOptionalBool(root, "clamp", false);
        var name = GetOptionalString(root, "name");
        var captured = GetOptional(root, "captured");

        SketchFootPointOnCurveImpl(sketch, point, curve, mode, clamp, name, captured);

        return default;
    }

    /// <summary>
    /// Returns vertices of sketch geometry in sketch coordinates (2D). Vertices are derived from the topology of the selected sketch entities/regions (e.g., polycurve/rectangle/ngon vertices, arc/line endpoints, and region boundary vertices after boolean/offset operations). If 'sketchGeometry' is omitted, all eligible entities in the sketch are processed. If 'name' is provided, the resulting vertex set is stored in the workspace under this name. If 'suffix' is true, individual vertices are also stored as workspace points named &lt;base&gt;_&lt;i&gt; (0-based), where &lt;base&gt; is 'name'. The operation may return multiple disjoint vertex loops; vertices are returned in a deterministic order per loop as provided by the kernel.
    /// </summary>
    private JsonNode SketchGetVertices(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var sketchGeometry = GetOptional(root, "sketchGeometry");
        var name = GetOptionalString(root, "name");
        var suffix = GetOptionalBool(root, "suffix", false);
        var includeEndpoints = GetOptionalBool(root, "includeEndpoints", true);
        var unique = GetOptionalBool(root, "unique", false);
        var tolerance = GetOptionalDouble(root, "tolerance", double.NaN);

        SketchGetVerticesImpl(sketch, sketchGeometry, name, suffix, includeEndpoints, unique, tolerance);

        return default;
    }

    /// <summary>
    /// Computes intersection points between two sketch geometries.
    /// </summary>
    private JsonNode SketchIntersections(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var a = RequireProperty(root, "a");
        var b = RequireProperty(root, "b");
        var mode = GetOptionalString(root, "mode");
        var tolerance = GetOptionalDouble(root, "tolerance", double.NaN);
        var name = GetOptionalString(root, "name");
        var suffix = GetOptionalBool(root, "suffix", true);

        SketchIntersectionsImpl(sketch, a, b, mode, tolerance, name, suffix);

        return default;
    }

    /// <summary>
    /// Offsets sketch geometry by a given signed distance. Closed inputs produce parallel contours (region offsets). Open inputs produce equidistant curves. For open curves, positive distance offsets to the right side of the curve parameter direction, negative distance to the left side. If 'makeRegion' is true and the input is open, the tool attempts to create a closed region by combining the original curve and its offset (connecting corresponding end points). The operation may produce multiple disjoint results, including regions with holes, depending on the input geometry and distance. If 'sketchGeometry' is omitted, all eligible entities in the sketch are offset.
    /// </summary>
    private JsonNode SketchOffset(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var sketchGeometry = GetOptional(root, "sketchGeometry");
        var distance = RequireDouble(root, "distance");
        var joinType = GetOptionalString(root, "joinType");
        var miterLimit = GetOptionalDouble(root, "miterLimit", double.NaN);
        var makeRegion = GetOptionalBool(root, "makeRegion", false);
        var capType = GetOptionalString(root, "capType");
        var name = GetOptionalString(root, "name");

        SketchOffsetImpl(sketch, sketchGeometry, distance, joinType, miterLimit, makeRegion, capType, name);

        return default;
    }

    /// <summary>
    /// Creates a line perpendicular to a given line through a specified point.
    /// </summary>
    private JsonNode SketchPerpendicularThrough(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var line = RequireProperty(root, "line");
        var point = RequirePoint2D(root, "point");
        var length = GetOptionalDouble(root, "length", 1);
        var name = GetOptionalString(root, "name");

        SketchPerpendicularThroughImpl(sketch, line, point, length, name);

        return default;
    }

    /// <summary>
    /// Rounds (fillets) vertices of sketch entities. If entity is omitted, applies to all eligible entities in the sketch. Vertex selection can be done by proximity points (2D) or by vertex indices (for entities with an ordered vertex list such as polycurve/rectangle/ngon). If neither points nor indices are provided, all vertices are rounded. If name is omitted, the operation overwrites the original entity (same name as the source). If name is provided, a new entity is created and the original remains.
    /// </summary>
    private JsonNode SketchRoundVertices(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var entity = GetOptional(root, "entity");
        var radius = RequireDouble(root, "radius");
        var nearPoints = GetOptional(root, "nearPoints");
        var indices = GetOptional(root, "indices");
        var tolerance = GetOptionalDouble(root, "tolerance", double.NaN);
        var name = GetOptionalString(root, "name");

        SketchRoundVerticesImpl(sketch, entity, radius, nearPoints, indices, tolerance, name);

        return default;
    }

    /// <summary>
    /// Sets the start point and/or end point of a line, circle, or arc in a sketch. For a full circle, setting endpoints converts it into an arc. For arcs, direction can be controlled explicitly so arcs greater than 180 degrees can be created. Optionally, the original radius can be preserved when adjusting circle or arc endpoints.
    /// </summary>
    private JsonNode SketchSetCurveEndpoints(JsonElement root)
    {
        AssertIsObject(root);
        var sketch = RequireObjectRef<Sketch>(root, "sketch");;
        var curve = RequireProperty(root, "curve");
        var start = GetOptionalPoint2D(root, "start", GeoPoint2D.Invalid);
        var end = GetOptionalPoint2D(root, "end", GeoPoint2D.Invalid);
        var direction = GetOptionalString(root, "direction");
        var projectToCurve = GetOptionalBool(root, "projectToCurve", false);
        var copy = GetOptionalBool(root, "copy", false);
        var name = GetOptionalString(root, "name");
        var capture = GetOptional(root, "capture");

        SketchSetCurveEndpointsImpl(sketch, curve, start, end, direction, projectToCurve, copy, name, capture);

        return default;
    }

    /// <summary>
    /// Performs a boolean operation on solids. The first operand is the target (and defines the default name). The second operand can be a single solid or a list of solids. Does not modify inputs; returns a new solid. Supports automatic topology rebind (default: rebind=true) after the operation so that named faces/edges remain usable across boolean changes.
    /// </summary>
    private JsonNode SolidBoolean(JsonElement root)
    {
        AssertIsObject(root);
        var op = RequireString(root, "op");
        var a = RequireProperty(root, "a");
        var b = RequireProperty(root, "b");
        var name = GetOptionalString(root, "name");
        var rebind = GetOptionalBool(root, "rebind", true);
        var rebindTargets = GetOptional(root, "rebindTargets");

        SolidBooleanImpl(op, a, b, name, rebind, rebindTargets);

        return default;
    }

    /// <summary>
    /// Creates a box solid defined by an origin point and three edge lengths along a local coordinate system.
    /// </summary>
    private JsonNode SolidBox(JsonElement root)
    {
        AssertIsObject(root);
        var origin = RequirePoint3D(root, "origin");
        var axisX = GetOptionalVector3D(root, "axisX", GeoVector.Invalid);
        var axisY = GetOptionalVector3D(root, "axisY", GeoVector.Invalid);
        var sizeX = RequireDouble(root, "sizeX");
        var sizeY = RequireDouble(root, "sizeY");
        var sizeZ = RequireDouble(root, "sizeZ");
        var name = GetOptionalString(root, "name");

        SolidBoxImpl(origin, axisX, axisY, sizeX, sizeY, sizeZ, name);

        return default;
    }

    /// <summary>
    /// Creates a capsule solid defined by two axis points and a radius.
    /// </summary>
    private JsonNode SolidCapsule(JsonElement root)
    {
        AssertIsObject(root);
        var start = RequirePoint3D(root, "start");
        var end = RequirePoint3D(root, "end");
        var radius = RequireDouble(root, "radius");
        var cap = GetOptionalString(root, "cap");
        var coneTipDistance = GetOptionalDouble(root, "coneTipDistance", double.NaN);
        var name = GetOptionalString(root, "name");

        SolidCapsuleImpl(start, end, radius, cap, coneTipDistance, name);

        return default;
    }

    /// <summary>
    /// Creates a cone or conical frustum solid.
    /// </summary>
    private JsonNode SolidCone(JsonElement root)
    {
        AssertIsObject(root);
        var start = RequirePoint3D(root, "start");
        var end = RequirePoint3D(root, "end");
        var radiusStart = RequireDouble(root, "radiusStart");
        var radiusEnd = RequireDouble(root, "radiusEnd");
        var name = GetOptionalString(root, "name");

        SolidConeImpl(start, end, radiusStart, radiusEnd, name);

        return default;
    }

    /// <summary>
    /// Creates a cylinder solid defined by two axis points and a radius.
    /// </summary>
    private JsonNode SolidCylinder(JsonElement root)
    {
        AssertIsObject(root);
        var start = RequirePoint3D(root, "start");
        var end = RequirePoint3D(root, "end");
        var radius = RequireDouble(root, "radius");
        var name = GetOptionalString(root, "name");

        SolidCylinderImpl(start, end, radius, name);

        return default;
    }

    /// <summary>
    /// Extrudes a profile into a new solid body. direction defaults to profile/sketch normal. The extrusion spans from offset to offset+length along direction. Returns the new solid. Optionally captures start/end faces and profile-edge loops as named sets. Note: profile is resolved via Selector (expected sketch geometry or sketch with closed loops).
    /// </summary>
    private JsonNode SolidExtrude(JsonElement root)
    {
        AssertIsObject(root);
        var profile = RequireProperty(root, "profile");
        var length = RequireDouble(root, "length");
        var direction = GetOptionalVector3D(root, "direction", GeoVector.Invalid);
        var offset = GetOptionalDouble(root, "offset", 0);
        var name = GetOptionalString(root, "name");
        var capture = GetOptional(root, "capture");

        SolidExtrudeImpl(profile, length, direction, offset, name, capture);

        return default;
    }

    /// <summary>
    /// Creates a new solid by helical extrusion of a planar profile around a given axis. The profile is rotated around the axis while simultaneously translated along it according to the specified pitch. Returns the new solid. Optionally captures start/end faces and profile-edge loops as named topology sets. Note: profile is resolved via Selector and is expected to refer to closed sketch geometry or a sketch containing closed loops.
    /// </summary>
    private JsonNode SolidHelicalExtrude(JsonElement root)
    {
        AssertIsObject(root);
        var profile = RequireProperty(root, "profile");
        var axis = RequireAxis3D(root, "axis");
        var angle = RequireAngle(root, "angle");
        var offset = GetOptionalDouble(root, "offset", double.NaN);
        var pitch = RequireDouble(root, "pitch");
        var name = GetOptionalString(root, "name");
        var capture = GetOptional(root, "capture");

        SolidHelicalExtrudeImpl(profile, axis, angle, offset, pitch, name, capture);

        return default;
    }

    /// <summary>
    /// Creates a hollow cylindrical pipe solid.
    /// </summary>
    private JsonNode SolidPipe(JsonElement root)
    {
        AssertIsObject(root);
        var start = RequirePoint3D(root, "start");
        var end = RequirePoint3D(root, "end");
        var outerRadius = RequireDouble(root, "outerRadius");
        var innerRadius = RequireDouble(root, "innerRadius");
        var name = GetOptionalString(root, "name");

        SolidPipeImpl(start, end, outerRadius, innerRadius, name);

        return default;
    }

    /// <summary>
    /// Revolves a planar profile around an axis to create a new solid body (revolve). angle can be full rotation or degrees. Returns the new solid. For partial revolves, start/end cap faces may be captured. Note: profile is resolved via Selector.
    /// </summary>
    private JsonNode SolidRotate(JsonElement root)
    {
        AssertIsObject(root);
        var profile = RequireProperty(root, "profile");
        var axis = RequireAxis3D(root, "axis");
        var angle = RequireAngle(root, "angle");
        var name = GetOptionalString(root, "name");
        var capture = GetOptional(root, "capture");

        SolidRotateImpl(profile, axis, angle, name, capture);

        return default;
    }

    /// <summary>
    /// Creates a solid by connecting two closed sketch profiles with ruled surfaces. Corresponding points on the two profiles are connected by straight line segments. The profiles must be closed sketch geometries.
    /// </summary>
    private JsonNode SolidRuled(JsonElement root)
    {
        AssertIsObject(root);
        var profile1 = RequireProperty(root, "profile1");
        var profile2 = RequireProperty(root, "profile2");
        var synchronization = GetOptionalString(root, "synchronization");
        var alignment = GetOptionalString(root, "alignment");
        var matchPoints1 = GetOptional(root, "matchPoints1");
        var matchPoints2 = GetOptional(root, "matchPoints2");
        var name = GetOptionalString(root, "name");

        SolidRuledImpl(profile1, profile2, synchronization, alignment, matchPoints1, matchPoints2, name);

        return default;
    }

    /// <summary>
    /// Creates a sphere solid. The sphere can be defined using different equivalent parameter sets.
    /// </summary>
    private JsonNode SolidSphere(JsonElement root)
    {
        AssertIsObject(root);
        var center = GetOptionalPoint3D(root, "center", GeoPoint.Invalid);
        var radius = GetOptionalDouble(root, "radius", double.NaN);
        var points = GetOptional(root, "points");
        var name = GetOptionalString(root, "name");

        SolidSphereImpl(center, radius, points, name);

        return default;
    }

    /// <summary>
    /// Sweeps a profile along a path curve to create a new solid body. Path is a 3D curve or polycurve. Orientation defaults to 'follow' (Frenet/transport). Returns the new solid. Optionally captures start/end faces and profile-edge loops. Note: profile is resolved via Selector. Note: path is resolved via Selector (expected single path/curve).
    /// </summary>
    private JsonNode SolidSweep(JsonElement root)
    {
        AssertIsObject(root);
        var profile = RequireProperty(root, "profile");
        var path = RequireProperty(root, "path");
        var orientation = GetOptionalString(root, "orientation");
        var name = GetOptionalString(root, "name");
        var capture = GetOptional(root, "capture");

        SolidSweepImpl(profile, path, orientation, name, capture);

        return default;
    }

    /// <summary>
    /// Creates a torus solid defined by center, axis, major radius and minor radius.
    /// </summary>
    private JsonNode SolidTorus(JsonElement root)
    {
        AssertIsObject(root);
        var center = RequirePoint3D(root, "center");
        var axis = RequireVector3D(root, "axis");
        var majorRadius = RequireDouble(root, "majorRadius");
        var minorRadius = RequireDouble(root, "minorRadius");
        var name = GetOptionalString(root, "name");

        SolidTorusImpl(center, axis, majorRadius, minorRadius, name);

        return default;
    }

    /// <summary>
    /// Creates a parametric surface from three expressions x(u,v), y(u,v), z(u,v) over a rectangular parameter domain. The surface is internally approximated by a NURBS surface and can be used as an unbounded carrier surface for later operations such as solid splitting.
    /// </summary>
    private JsonNode SurfaceParametric(JsonElement root)
    {
        AssertIsObject(root);
        var degreeU = GetOptionalInteger(root, "degreeU", 3);
        var degreeV = GetOptionalInteger(root, "degreeV", 3);
        var approximation = RequireProperty(root, "approximation");
        var name = GetOptionalString(root, "name");

        SurfaceParametricImpl(degreeU, degreeV, approximation, name);

        return default;
    }

    /// <summary>
    /// Returns information about the active MCP toolset definition loaded by the server.
    /// </summary>
    private JsonNode SystemGetInfo(JsonElement root)
    {
        AssertIsObject(root);

        SystemGetInfoImpl();

        var result = new JsonObject();
        result["toolsetId"] = null; // TODO
        result["toolsetVersion"] = null; // TODO
        result["schemaVersion"] = null; // TODO
        result["generatedAt"] = null; // TODO
        result["toolsHash"] = null; // TODO
        return result;
    }

    /// <summary>
    /// Begins recording a parametric template. Subsequent RPC calls are recorded as the template construction body until template.commit is called. Template parameters become available as local workspace values during recording.
    /// </summary>
    private JsonNode TemplateBegin(JsonElement root)
    {
        AssertIsObject(root);
        var name = RequireString(root, "name");
        var label = GetOptionalString(root, "label");
        var description = GetOptionalString(root, "description");
        var category = GetOptionalString(root, "category");
        var tags = GetOptional(root, "tags");
        var parameters = RequireProperty(root, "parameters");
        var allowDocumentCommit = GetOptionalBool(root, "allowDocumentCommit", false);

        TemplateBeginImpl(name, label, description, category, tags, parameters, allowDocumentCommit);

        return default;
    }

    /// <summary>
    /// Ends template recording and stores the recorded construction as a reusable parametric template.
    /// </summary>
    private JsonNode TemplateCommit(JsonElement root)
    {
        AssertIsObject(root);
        var result = RequireProperty(root, "result");
        var resultKind = GetOptionalString(root, "resultKind");
        var suffixInternalNames = GetOptionalBool(root, "suffixInternalNames", true);

        TemplateCommitImpl(result, resultKind, suffixInternalNames);

        return default;
    }

    /// <summary>
    /// Creates one instance of a previously defined template using explicit parameter values or template defaults.
    /// </summary>
    private JsonNode TemplateInstantiate(JsonElement root)
    {
        AssertIsObject(root);
        var template = RequireString(root, "template");
        var arguments = GetOptional(root, "arguments");
        var transform = GetOptionalString(root, "transform");
        var name = GetOptionalString(root, "name");
        var explodeResult = GetOptionalBool(root, "explodeResult", false);

        TemplateInstantiateImpl(template, arguments, transform, name, explodeResult);

        return default;
    }

    /// <summary>
    /// Translates one or more objects by a 3D vector. If copy=true, returns new objects; otherwise modifies originals. Returned objects are references to moved/copied objects. When copy=true, the server can also copy named topology references (copyNamed=true) and create new names using nameSuffix. Note: objects are resolved via Selector (may select one or many).
    /// </summary>
    private JsonNode TransformMove(JsonElement root)
    {
        AssertIsObject(root);
        var objects = RequireProperty(root, "objects");
        var delta = RequireVector3D(root, "delta");
        var name = GetOptionalString(root, "name");
        var copySuffix = GetOptionalString(root, "copySuffix");

        TransformMoveImpl(objects, delta, name, copySuffix);

        return default;
    }

    /// <summary>
    /// Reflects (mirrors) one or more objects across a plane. If copy=true, returns new objects; otherwise modifies originals. When copy=true, the server can also copy named topology references (copyNamed=true) and create new names using nameSuffix. Note: objects are resolved via Selector (may select one or many).
    /// </summary>
    private JsonNode TransformReflect(JsonElement root)
    {
        AssertIsObject(root);
        var objects = RequireProperty(root, "objects");
        var plane = GetOptionalPlane(root, "plane", Plane.Invalid);
        var axis3D = GetOptionalAxis3D(root, "axis3D", Axis.InvalidAxis);
        var axis2D = GetOptionalAxis2D(root, "axis2D", Axis2D.InvalidAxis);
        var name = GetOptionalString(root, "name");
        var copySuffix = GetOptionalString(root, "copySuffix");

        TransformReflectImpl(objects, plane, axis3D, axis2D, name, copySuffix);

        return default;
    }

    /// <summary>
    /// Rotates one or more objects around an axis by a given angle. If 'name' is omitted, the selected objects are rotated in place and keep their names. If 'name' is provided, copies are created, rotated, and captured as a named set. When multiple objects are copied, individual result names are derived from the original names by appending 'nameSuffix'.
    /// </summary>
    private JsonNode TransformRotate(JsonElement root)
    {
        AssertIsObject(root);
        var objects = RequireProperty(root, "objects");
        var axis = RequireAxis3D(root, "axis");
        var angle = RequireAngle(root, "angle");
        var name = GetOptionalString(root, "name");
        var copySuffix = GetOptionalString(root, "copySuffix");

        TransformRotateImpl(objects, axis, angle, name, copySuffix);

        return default;
    }

    /// <summary>
    /// Scales one or more objects about an origin. Provide either uniform factor or non-uniform factors (x,y,z). If copy=true, returns new objects; otherwise modifies originals. When copy=true, the server can also copy named topology references (copyNamed=true) and create new names using nameSuffix. Note: objects are resolved via Selector (may select one or many).
    /// </summary>
    private JsonNode TransformScale(JsonElement root)
    {
        AssertIsObject(root);
        var objects = RequireProperty(root, "objects");
        var origin = RequirePoint3D(root, "origin");
        var factor = GetOptionalDouble(root, "factor", double.NaN);
        var factors = GetOptional(root, "factors");
        var name = GetOptionalString(root, "name");
        var copySuffix = GetOptionalString(root, "copySuffix");

        TransformScaleImpl(objects, origin, factor, factors, name, copySuffix);

        return default;
    }

    /// <summary>
    /// Begins an undo frame. All subsequent committed changes until undo.end are grouped into one undo step. Returns undoFrameId.
    /// </summary>
    private JsonNode UndoBegin(JsonElement root)
    {
        AssertIsObject(root);
        var label = RequireString(root, "label");

        UndoBeginImpl(label);

        return default;
    }

    /// <summary>
    /// Cancels an undo frame started with undo.begin, rolling back all changes in that frame.
    /// </summary>
    private JsonNode UndoCancel(JsonElement root)
    {
        AssertIsObject(root);
        var undoFrameId = RequireString(root, "undoFrameId");

        UndoCancelImpl(undoFrameId);

        return default;
    }

    /// <summary>
    /// Ends an undo frame started with undo.begin. If errors occurred, server may auto-cancel the frame.
    /// </summary>
    private JsonNode UndoEnd(JsonElement root)
    {
        AssertIsObject(root);
        var undoFrameId = RequireString(root, "undoFrameId");

        UndoEndImpl(undoFrameId);

        return default;
    }

    /// <summary>
    /// Deletes one or more workspace objects (temporary objects not yet committed). Deleting a committed object is not allowed and returns E_INVALID_PARAMS. Note: objects are resolved via Selector (may select one or many).
    /// </summary>
    private JsonNode WorkspaceDelete(JsonElement root)
    {
        AssertIsObject(root);
        var objects = RequireProperty(root, "objects");

        WorkspaceDeleteImpl(objects);

        return default;
    }

    /// <summary>
    /// Defines or updates a named workspace value. Optionally, the value can be marked as a user-editable parameter with UI metadata such as label, input type, limits, and choices.
    /// </summary>
    private JsonNode WorkspaceSet(JsonElement root)
    {
        AssertIsObject(root);
        var name = RequireString(root, "name");
        var value = RequireProperty(root, "value");
        var label = GetOptionalString(root, "label");
        var input = GetOptional(root, "input");

        WorkspaceSetImpl(name, value, label, input);

        return default;
    }

}

